# coding: utf-8
# 
#
# user-graph need to be generated by the following script
# tools/generate-u-u-matrix.py
import os
import numpy as np
import scipy.sparse as sp
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn.conv import MessagePassing
from torch_geometric.utils import remove_self_loops, add_self_loops, degree
import torch_geometric

from common.abstract_recommender import GeneralRecommender
from common.loss import BPRLoss, EmbLoss
from common.init import xavier_uniform_initialization
from torch.nn import MultiheadAttention
# from .transformer import TransformerEncoder

class MASKED_GLORIA_EX(GeneralRecommender):
    def __init__(self, config, dataset):
        super(MASKED_GLORIA_EX, self).__init__(config, dataset)

        num_user = self.n_users
        num_item = self.n_items
        print('number of users: {}, number of items: {}'.format(num_user, num_item))
        
        batch_size = config['train_batch_size']         # not used
        dim_x = config['embedding_size']
        self.feat_embed_dim = config['feat_embed_dim']
        self.n_layers = config['n_mm_layers']
        self.knn_k = config['knn_k']

        self.batch_size = batch_size
        self.num_user = num_user
        self.num_item = num_item
        self.k = 40
        self.aggr_mode = config['aggr_mode']
        self.user_aggr_mode = 'softmax'
        self.num_layer = 1
        self.dataset = dataset
        self.reg_weight = config['reg_weight']
        self.drop_rate = 0.1
        self.t_rep = None
        self.t_preference = None
        self.dim_latent = 64
        self.mm_adj = None
        self.config = config
        dataset_path = os.path.abspath(config['data_path'] + config['dataset'])
        
        mm_adj_file = os.path.join(dataset_path, 'mm_adj_{}.pt'.format(self.knn_k))

        # self.id_embedding_low = nn.Embedding(num_item, self.feat_embed_dim)
        # self.id_embedding_high = nn.Embedding(num_item, self.feat_embed_dim)
        self.id_embedding_full = nn.Embedding(num_item, self.feat_embed_dim)
        self.id_embedding_masked = nn.Embedding(num_item, self.feat_embed_dim)

        self.mlp_item = nn.Linear(self.t_feat.shape[-1], self.dim_latent, bias=False)
        self.mlp_user = nn.Linear(self.user_feat.shape[-1], self.dim_latent, bias=False)

        indices, text_adj = self.get_knn_adj_mat(self.t_feat)
        self.mm_adj = text_adj

        train_interactions = dataset.inter_matrix(form='coo').astype(np.float32)

        edge_index = self.pack_edge_index(train_interactions)

        self.num_interactions = edge_index.shape[0]

        edge_index = torch.tensor(edge_index, 
                                  dtype=torch.long,
                                  device = self.device).t().contiguous()

        self.edge_index = torch.cat(
                            [edge_index, edge_index[[1, 0]]],
                            dim=1
                        )

        self.mask_logits = nn.Parameter(
                            torch.zeros(
                                self.num_interactions,
                                device=self.device
                            )
                        )

        # ------------------------------------------------------------
        # Counterfactual-aware adaptive fusion
        # ------------------------------------------------------------
        # The gate learns, for each user, how much to trust the factual
        # (full-graph) branch versus the counterfactual (masked-graph) branch.
        #
        # final score = g_u * score_full + (1 - g_u) * score_mask
        #
        # We implement this at representation level by weighting only the
        # user-side blocks before concatenation, so full_sort_predict can
        # remain a single matrix multiplication.
        self.cf_gate = nn.Sequential(
            nn.Linear(2 * self.feat_embed_dim, self.feat_embed_dim),
            nn.LeakyReLU(),
            nn.Linear(self.feat_embed_dim, 1)
        )

        # Start from g_u = 0.5 for every user. Together with the factor 2
        # in forward(), this exactly recovers the original score
        # score_full + score_mask at initialization.
        nn.init.zeros_(self.cf_gate[-1].weight)
        nn.init.zeros_(self.cf_gate[-1].bias)

        # Optional auxiliary BPR loss on the masked/counterfactual branch.
        # Set cf_bpr_weight = 0.0 to test the gate alone.
        self.cf_bpr_weight = float(config.get('cf_bpr_weight', 0.0))

        edge_index = self.pack_edge_index(train_interactions)

        item_ids = edge_index[:, 1] - self.num_user
        item_degree = np.bincount(item_ids, minlength=self.num_item)

        high_ratio = 0.10
        num_high = int(self.num_item * high_ratio)

        high_items = np.argsort(item_degree)[-num_high:]
        high_items = set(high_items.tolist())

        low_edges = []
        high_edges = []

        for edge in edge_index:
            item_id = edge[1] - self.num_user

            if item_id in high_items:
                high_edges.append(edge)
            else:
                low_edges.append(edge)

        low_edges = np.array(low_edges, dtype=np.int64)
        high_edges = np.array(high_edges, dtype=np.int64)

        self.edge_index_low = torch.tensor(low_edges, dtype=torch.long).t().contiguous().to(self.device)
        self.edge_index_high = torch.tensor(high_edges, dtype=torch.long).t().contiguous().to(self.device)

        self.edge_index_low = torch.cat(
            (self.edge_index_low, self.edge_index_low[[1, 0]]),
            dim=1
        )

        self.edge_index_high = torch.cat(
            (self.edge_index_high, self.edge_index_high[[1, 0]]),
            dim=1
        )
        # self.edge = concat 2 edge_index to make the graph undirected
        # self.edge_index = torch.cat((self.edge_index_low, self.edge_index_high), dim=1)

        # self.idl_gcn = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
        #                 num_layer=self.num_layer, has_feature=False, dropout=self.drop_rate, dim_latent=64,
        #                 device=self.device, features=self.id_embedding.weight)
        # self.idh_gcn = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
        #                 num_layer=self.num_layer, has_feature=False, dropout=self.drop_rate, dim_latent=64,
        #                 device=self.device, features=self.id_embedding.weight)

        self.full_gcn = GCN(
                        self.dataset,
                        batch_size,
                        num_user,
                        num_item,
                        dim_x,
                        self.aggr_mode,
                        num_layer=self.num_layer,
                        has_feature=False,
                        dropout=self.drop_rate,
                        dim_latent=64,
                        device=self.device,
                        features=self.id_embedding_full.weight
                    )

        self.mask_gcn = GCN(
            self.dataset,
            batch_size,
            num_user,
            num_item,
            dim_x,
            self.aggr_mode,
            num_layer=self.num_layer,
            has_feature=False,
            dropout=self.drop_rate,
            dim_latent=64,
            device=self.device,
            features=self.id_embedding_masked.weight
        )
        if config['fusion'] in ['add', 'pool']:
            pass
        elif config['fusion'] == 'Multi-Head Attention':
            self.multihead_attn = nn.MultiheadAttention(embed_dim=64, num_heads=4)
        elif config['fusion'] == 'Transformer':
            self.transformer = TransformerEncoder(64, num_heads= 4, layers=2)
        else:
            raise NotImplementedError
        


    def get_knn_adj_mat(self, mm_embeddings):
        context_norm = mm_embeddings.div(torch.norm(mm_embeddings, p=2, dim=-1, keepdim=True))
        sim = torch.mm(context_norm, context_norm.transpose(1, 0))
        _, knn_ind = torch.topk(sim, self.knn_k, dim=-1)
        adj_size = sim.size()
        del sim
        # construct sparse adj
        indices0 = torch.arange(knn_ind.shape[0]).to(self.device)
        indices0 = torch.unsqueeze(indices0, 1)
        indices0 = indices0.expand(-1, self.knn_k)
        indices = torch.stack((torch.flatten(indices0), torch.flatten(knn_ind)), 0)
        # norm
        return indices, self.compute_normalized_laplacian(indices, adj_size)
    
    def compute_normalized_laplacian(self, indices, adj_size):
        adj = torch.sparse.FloatTensor(indices, torch.ones_like(indices[0]), adj_size)
        row_sum = 1e-7 + torch.sparse.sum(adj, -1).to_dense()
        r_inv_sqrt = torch.pow(row_sum, -0.5)
        rows_inv_sqrt = r_inv_sqrt[indices[0]]
        cols_inv_sqrt = r_inv_sqrt[indices[1]]
        values = rows_inv_sqrt * cols_inv_sqrt
        return torch.sparse.FloatTensor(indices, values, adj_size)

    def pack_edge_index(self, inter_mat):
        rows = inter_mat.row
        cols = inter_mat.col + self.n_users
        return np.column_stack((rows, cols))

    def item_item(self, rep):
        h = rep
        for i in range(self.n_layers):
            h = torch.sparse.mm(self.mm_adj, h)
        return rep + h

    def forward(self, interaction):
        user_nodes = interaction[0]

        # Keep item ids in local item space for branch-specific scores.
        # Do not modify interaction in-place.
        pos_item_local = interaction[1]
        neg_item_local = interaction[2]

        pos_item_nodes = pos_item_local + self.n_users
        neg_item_nodes = neg_item_local + self.n_users

        # ============================================================
        # 1. Factual branch: full interaction graph
        # ============================================================
        self.full_rep, self.full_preference = self.full_gcn(
            self.edge_index,
            self.id_embedding_full.weight
        )

        # ============================================================
        # 2. Counterfactual branch: learnable masked graph
        # ============================================================
        mask = torch.sigmoid(self.mask_logits)
        self.current_mask = mask

        # edge_index contains original edges followed by reverse edges,
        # therefore the same learned weight is reused in both directions.
        edge_mask = torch.cat([mask, mask], dim=0)

        self.mask_rep, self.mask_preference = self.mask_gcn(
            self.edge_index,
            self.id_embedding_masked.weight,
            edge_mask=edge_mask
        )

        # ============================================================
        # 3. Split user/item representations for the two worlds
        # ============================================================
        user_full = self.full_rep[:self.num_user]
        item_full = self.full_rep[self.num_user:]

        user_cf = self.mask_rep[:self.num_user]
        item_cf = self.mask_rep[self.num_user:]

        self.user_full_rep = user_full
        self.item_full_rep = item_full
        self.user_cf_rep = user_cf
        self.item_cf_rep = item_cf

        # ============================================================
        # 4. Counterfactual-aware user gate
        # ============================================================
        # g_u close to 1 -> trust the full/factual branch more
        # g_u close to 0 -> trust the masked/counterfactual branch more
        user_gate = torch.sigmoid(
            self.cf_gate(
                torch.cat([user_full, user_cf], dim=1)
            )
        )

        self.user_cf_gate = user_gate

        # Important trick:
        #   [2g*u_full || 2(1-g)*u_cf]^T [i_full || i_cf]
        # = 2g * <u_full, i_full> + 2(1-g) * <u_cf, i_cf>
        #
        # At initialization g = 0.5, therefore this is exactly
        # <u_full, i_full> + <u_cf, i_cf>, i.e. your original concat score.
        # The model can then move g away from 0.5 only when useful.
        user_rep = torch.cat(
            [
                2.0 * user_gate * user_full,
                2.0 * (1.0 - user_gate) * user_cf
            ],
            dim=1
        )

        item_rep = torch.cat(
            [item_full, item_cf],
            dim=1
        )

        # Preserve your original item-item graph propagation. Because this
        # operation is linear and acts independently on feature dimensions,
        # the two concatenated branch blocks remain separable.
        item_rep = self.item_item(item_rep)

        branch_dim = item_full.size(1)
        item_full_final = item_rep[:, :branch_dim]
        item_cf_final = item_rep[:, branch_dim:]

        self.result_embed = torch.cat((user_rep, item_rep), dim=0)

        user_tensor = self.result_embed[user_nodes]
        pos_item_tensor = self.result_embed[pos_item_nodes]
        neg_item_tensor = self.result_embed[neg_item_nodes]

        pos_scores = torch.sum(user_tensor * pos_item_tensor, dim=1)
        neg_scores = torch.sum(user_tensor * neg_item_tensor, dim=1)

        # ============================================================
        # 5. Optional counterfactual-only scores for auxiliary CF-BPR
        # ============================================================
        cf_user_batch = user_cf[user_nodes]
        cf_pos_item_batch = item_cf_final[pos_item_local]
        cf_neg_item_batch = item_cf_final[neg_item_local]

        cf_pos_scores = torch.sum(
            cf_user_batch * cf_pos_item_batch,
            dim=1
        )
        cf_neg_scores = torch.sum(
            cf_user_batch * cf_neg_item_batch,
            dim=1
        )

        return pos_scores, neg_scores, cf_pos_scores, cf_neg_scores

    def calculate_loss(self, interaction):
        (
            pos_scores,
            neg_scores,
            cf_pos_scores,
            cf_neg_scores
        ) = self.forward(interaction)

        # Main BPR loss from adaptively fused factual + counterfactual score.
        main_loss = -torch.mean(
            torch.log2(
                torch.sigmoid(pos_scores - neg_scores).clamp_min(1e-12)
            )
        )

        # Optional auxiliary loss: the masked/counterfactual branch should
        # remain recommendation-useful on its own.
        if self.cf_bpr_weight > 0.0:
            cf_loss = -torch.mean(
                torch.log2(
                    torch.sigmoid(
                        cf_pos_scores - cf_neg_scores
                    ).clamp_min(1e-12)
                )
            )
            loss_value = main_loss + self.cf_bpr_weight * cf_loss
        else:
            cf_loss = main_loss.new_zeros(())
            loss_value = main_loss

        # Useful for logging/debugging without changing trainer API.
        self.last_main_loss = main_loss.detach()
        self.last_cf_loss = cf_loss.detach()

        return loss_value

    @torch.no_grad()
    def get_cf_gate_statistics(self):
        """Return simple diagnostics for the learned user gate."""
        if not hasattr(self, 'user_cf_gate'):
            return {}

        gate = self.user_cf_gate.squeeze(-1)
        return {
            'mean_full_weight': gate.mean().item(),
            'mean_cf_weight': (1.0 - gate).mean().item(),
            'min_full_weight': gate.min().item(),
            'max_full_weight': gate.max().item(),
            'fraction_full_dominant': (gate > 0.5).float().mean().item(),
            'fraction_cf_dominant': (gate < 0.5).float().mean().item(),
        }

    def full_sort_predict(self, interaction):
        user_tensor = self.result_embed[:self.n_users]
        item_tensor = self.result_embed[self.n_users:]

        temp_user_tensor = user_tensor[interaction[0], :]
        score_matrix = torch.matmul(temp_user_tensor, item_tensor.t())
        return score_matrix

class GCN(torch.nn.Module):
    def __init__(self,datasets, batch_size, num_user, num_item, dim_id, aggr_mode, num_layer, has_feature, dropout,
                 dim_latent=None,device = None,features=None, user_profile=None):
        super(GCN, self).__init__()
        self.batch_size = batch_size
        self.num_user = num_user
        self.num_item = num_item
        self.datasets = datasets
        self.dim_id = dim_id
        self.dim_feat = features.size(1)
        self.dim_latent = dim_latent
        self.aggr_mode = aggr_mode
        self.has_feature = has_feature
        self.dropout = dropout
        self.device = device
        self.userprofile = user_profile

        if self.has_feature:
            self.preference = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
                np.random.randn(num_user, self.dim_latent), dtype=torch.float32, requires_grad=True),
                gain=1))
            self.conv_embed_1 = Base_gcn(self.dim_latent, self.dim_latent, aggr=self.aggr_mode)
        else:
            self.preference = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
                np.random.randn(num_user, self.dim_feat), dtype=torch.float32, requires_grad=True),
                gain=1))
            self.conv_embed_1 = Base_gcn(self.dim_latent, self.dim_latent, aggr=self.aggr_mode)

    def forward(self,edge_index,features, edge_mask = None):
        temp_features = features
        temp_profile = self.preference
        x = torch.cat((temp_profile, temp_features), dim=0)
        x = F.normalize(x)
        h = self.conv_embed_1(x, edge_index,edge_mask)  # equation 1
        h_1 = self.conv_embed_1(h, edge_index,edge_mask)  # equation 1
        h_2 = self.conv_embed_1(h_1, edge_index,edge_mask)

        x_hat =h + x + h_1 + h_2
        return x_hat, self.preference


class Base_gcn(MessagePassing):
    def __init__(self, in_channels, out_channels, normalize=True, bias=True, aggr='add', **kwargs):
        super(Base_gcn, self).__init__(aggr=aggr, **kwargs)
        self.aggr = aggr
        self.in_channels = in_channels
        self.out_channels = out_channels

    def forward(self, x, edge_index,edge_mask=None, size=None):
        # pdb.set_trace()

        if edge_mask is None:
            edge_mask = torch.ones(
                edge_index.size(1),
                device=x.device,
                dtype=x.dtype
            )

        if size is None:
            edge_index, _ = remove_self_loops(edge_index)
            # edge_index, _ = add_self_loops(edge_index, num_nodes=x.size(0))
        x = x.unsqueeze(-1) if x.dim() == 1 else x
        # pdb.set_trace()
        return self.propagate(edge_index, size=(x.size(0), x.size(0)), x=x, edge_mask = edge_mask)

    def message(self, x_j, edge_index, size,edge_mask):
        if self.aggr == 'add':
            # pdb.set_trace()
            row, col = edge_index
            deg = degree(row, size[0], dtype=x_j.dtype)
            deg_inv_sqrt = deg.pow(-0.5)
            deg_inv_sqrt[
            torch.isinf(deg_inv_sqrt)
            ] = 0

            norm = deg_inv_sqrt[row] * deg_inv_sqrt[col]
            # return norm.view(-1, 1) * x_j
            return (
                norm.view(-1, 1)
                * edge_mask.view(-1, 1)
                * x_j
            )
        return x_j

    def update(self, aggr_out):
        return aggr_out

    def __repr(self):
        return '{}({},{})'.format(self.__class__.__name__, self.in_channels, self.out_channels)


