# # coding: utf-8
# # 
# #
# # user-graph need to be generated by the following script
# # tools/generate-u-u-matrix.py
# import os
# import numpy as np
# import scipy.sparse as sp
# import torch
# import torch.nn as nn
# import torch.nn.functional as F
# from torch_geometric.nn.conv import MessagePassing
# from torch_geometric.utils import remove_self_loops, add_self_loops, degree
# import torch_geometric

# from common.abstract_recommender import GeneralRecommender
# from common.loss import BPRLoss, EmbLoss
# from common.init import xavier_uniform_initialization
# from torch.nn import MultiheadAttention
# # from .transformer import TransformerEncoder

# class MASKED_GLORIA_EX(GeneralRecommender):
#     def __init__(self, config, dataset):
#         super(MASKED_GLORIA_EX, self).__init__(config, dataset)

#         num_user = self.n_users
#         num_item = self.n_items
#         print('number of users: {}, number of items: {}'.format(num_user, num_item))
        
#         batch_size = config['train_batch_size']         # not used
#         dim_x = config['embedding_size']
#         self.feat_embed_dim = config['feat_embed_dim']
#         self.n_layers = config['n_mm_layers']
#         self.knn_k = config['knn_k']

#         self.batch_size = batch_size
#         self.num_user = num_user
#         self.num_item = num_item
#         self.k = 40
#         self.aggr_mode = config['aggr_mode']
#         self.user_aggr_mode = 'softmax'
#         self.num_layer = 1
#         self.dataset = dataset
#         self.reg_weight = config['reg_weight']
#         self.drop_rate = 0.1
#         self.t_rep = None
#         self.t_preference = None
#         self.dim_latent = 64
#         self.mm_adj = None
#         self.config = config
#         dataset_path = os.path.abspath(config['data_path'] + config['dataset'])
        
#         mm_adj_file = os.path.join(dataset_path, 'mm_adj_{}.pt'.format(self.knn_k))

#         # self.id_embedding_low = nn.Embedding(num_item, self.feat_embed_dim)
#         # self.id_embedding_high = nn.Embedding(num_item, self.feat_embed_dim)
#         self.id_embedding_full = nn.Embedding(num_item, self.feat_embed_dim)
#         self.id_embedding_masked = nn.Embedding(num_item, self.feat_embed_dim)

#         self.mlp_item = nn.Linear(self.t_feat.shape[-1], self.dim_latent, bias=False)
#         self.mlp_user = nn.Linear(self.user_feat.shape[-1], self.dim_latent, bias=False)

#         indices, text_adj = self.get_knn_adj_mat(self.t_feat)
#         self.mm_adj = text_adj

#         train_interactions = dataset.inter_matrix(form='coo').astype(np.float32)

#         edge_index = self.pack_edge_index(train_interactions)

#         self.num_interactions = edge_index.shape[0]

#         edge_index = torch.tensor(edge_index, 
#                                   dtype=torch.long,
#                                   device = self.device).t().contiguous()

#         self.edge_index = torch.cat(
#                             [edge_index, edge_index[[1, 0]]],
#                             dim=1
#                         )

#         self.mask_logits = nn.Parameter(
#                             torch.zeros(
#                                 self.num_interactions,
#                                 device=self.device
#                             )
#                         )

#         edge_index = self.pack_edge_index(train_interactions)

#         item_ids = edge_index[:, 1] - self.num_user
#         item_degree = np.bincount(item_ids, minlength=self.num_item)

#         high_ratio = 0.10
#         num_high = int(self.num_item * high_ratio)

#         high_items = np.argsort(item_degree)[-num_high:]
#         high_items = set(high_items.tolist())

#         low_edges = []
#         high_edges = []

#         for edge in edge_index:
#             item_id = edge[1] - self.num_user

#             if item_id in high_items:
#                 high_edges.append(edge)
#             else:
#                 low_edges.append(edge)

#         low_edges = np.array(low_edges, dtype=np.int64)
#         high_edges = np.array(high_edges, dtype=np.int64)

#         self.edge_index_low = torch.tensor(low_edges, dtype=torch.long).t().contiguous().to(self.device)
#         self.edge_index_high = torch.tensor(high_edges, dtype=torch.long).t().contiguous().to(self.device)

#         self.edge_index_low = torch.cat(
#             (self.edge_index_low, self.edge_index_low[[1, 0]]),
#             dim=1
#         )

#         self.edge_index_high = torch.cat(
#             (self.edge_index_high, self.edge_index_high[[1, 0]]),
#             dim=1
#         )
#         # self.edge = concat 2 edge_index to make the graph undirected
#         # self.edge_index = torch.cat((self.edge_index_low, self.edge_index_high), dim=1)

#         # self.idl_gcn = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
#         #                 num_layer=self.num_layer, has_feature=False, dropout=self.drop_rate, dim_latent=64,
#         #                 device=self.device, features=self.id_embedding.weight)
#         # self.idh_gcn = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
#         #                 num_layer=self.num_layer, has_feature=False, dropout=self.drop_rate, dim_latent=64,
#         #                 device=self.device, features=self.id_embedding.weight)

#         self.full_gcn = GCN(
#                         self.dataset,
#                         batch_size,
#                         num_user,
#                         num_item,
#                         dim_x,
#                         self.aggr_mode,
#                         num_layer=self.num_layer,
#                         has_feature=False,
#                         dropout=self.drop_rate,
#                         dim_latent=64,
#                         device=self.device,
#                         features=self.id_embedding_full.weight
#                     )

#         self.mask_gcn = GCN(
#             self.dataset,
#             batch_size,
#             num_user,
#             num_item,
#             dim_x,
#             self.aggr_mode,
#             num_layer=self.num_layer,
#             has_feature=False,
#             dropout=self.drop_rate,
#             dim_latent=64,
#             device=self.device,
#             features=self.id_embedding_masked.weight
#         )
#         if config['fusion'] in ['add', 'pool']:
#             pass
#         elif config['fusion'] == 'Multi-Head Attention':
#             self.multihead_attn = nn.MultiheadAttention(embed_dim=64, num_heads=4)
#         elif config['fusion'] == 'Transformer':
#             self.transformer = TransformerEncoder(64, num_heads= 4, layers=2)
#         else:
#             raise NotImplementedError
        


#     def get_knn_adj_mat(self, mm_embeddings):
#         context_norm = mm_embeddings.div(torch.norm(mm_embeddings, p=2, dim=-1, keepdim=True))
#         sim = torch.mm(context_norm, context_norm.transpose(1, 0))
#         _, knn_ind = torch.topk(sim, self.knn_k, dim=-1)
#         adj_size = sim.size()
#         del sim
#         # construct sparse adj
#         indices0 = torch.arange(knn_ind.shape[0]).to(self.device)
#         indices0 = torch.unsqueeze(indices0, 1)
#         indices0 = indices0.expand(-1, self.knn_k)
#         indices = torch.stack((torch.flatten(indices0), torch.flatten(knn_ind)), 0)
#         # norm
#         return indices, self.compute_normalized_laplacian(indices, adj_size)
    
#     def compute_normalized_laplacian(self, indices, adj_size):
#         adj = torch.sparse.FloatTensor(indices, torch.ones_like(indices[0]), adj_size)
#         row_sum = 1e-7 + torch.sparse.sum(adj, -1).to_dense()
#         r_inv_sqrt = torch.pow(row_sum, -0.5)
#         rows_inv_sqrt = r_inv_sqrt[indices[0]]
#         cols_inv_sqrt = r_inv_sqrt[indices[1]]
#         values = rows_inv_sqrt * cols_inv_sqrt
#         return torch.sparse.FloatTensor(indices, values, adj_size)

#     def pack_edge_index(self, inter_mat):
#         rows = inter_mat.row
#         cols = inter_mat.col + self.n_users
#         return np.column_stack((rows, cols))

#     def item_item(self, rep):
#         h = rep
#         for i in range(self.n_layers):
#             h = torch.sparse.mm(self.mm_adj, h)
#         return rep + h

#     def forward(self, interaction):
#         user_nodes, pos_item_nodes, neg_item_nodes = interaction[0], interaction[1], interaction[2]
#         pos_item_nodes += self.n_users
#         neg_item_nodes += self.n_users

#         # item_feat = self.mlp_item(self.t_feat)
#         # user_feat = F.normalize(self.mlp_user(self.user_feat))
        
#         # self.idl_rep, self.t_preference = self.idl_gcn(self.edge_index, self.id_embedding_low.weight)
#         # self.idh_rep, self.id_preference = self.idh_gcn(self.edge_index, self.id_embedding_high.weight)

#         self.full_rep, self.full_preference = self.full_gcn(
#                                                 self.edge_index,
#                                                 self.id_embedding_full.weight
#                                             )

#         mask = torch.sigmoid(self.mask_logits)

#         edge_mask = torch.cat(
#                         [mask, mask],
#                         dim=0
#                     )

#         self.mask_rep, self.mask_preference = self.mask_gcn(
#                                                 self.edge_index,
#                                                 self.id_embedding_masked.weight,
#                                                 edge_mask=edge_mask
#                                             )

#         item_repl = self.full_rep[self.num_user:]
#         item_reph = self.mask_rep[self.num_user:]

#         item_rep = torch.cat((item_repl, item_reph), dim=1)
#         item_rep = self.item_item(item_rep)

#         user_repl = self.full_rep[:self.num_user]
#         user_reph = self.mask_rep[:self.num_user]

#         user_rep = torch.cat((user_repl, user_reph), dim=1)

#         self.result_embed = torch.cat((user_rep, item_rep), dim=0)
#         user_tensor = self.result_embed[user_nodes]
#         pos_item_tensor = self.result_embed[pos_item_nodes]
#         neg_item_tensor = self.result_embed[neg_item_nodes]
#         pos_scores = torch.sum(user_tensor * pos_item_tensor, dim=1)
#         neg_scores = torch.sum(user_tensor * neg_item_tensor, dim=1)
#         return pos_scores, neg_scores

#     def calculate_loss(self, interaction):
#         pos_scores, neg_scores = self.forward(interaction)
#         bpr_loss = -torch.mean(torch.log2(torch.sigmoid(pos_scores - neg_scores)))

#         mask = torch.sigmoid(
#         self.mask_logits
#         )
#         self.lambda_cf = 0.1

#         cf_mask_loss = (
#             1.0 - mask
#         ).mean()

#         loss = (
#             bpr_loss
#             + self.lambda_cf * cf_mask_loss
#         )
#         return loss

#     def full_sort_predict(self, interaction):
#         user_tensor = self.result_embed[:self.n_users]
#         item_tensor = self.result_embed[self.n_users:]

#         temp_user_tensor = user_tensor[interaction[0], :]
#         score_matrix = torch.matmul(temp_user_tensor, item_tensor.t())
#         return score_matrix

# class GCN(torch.nn.Module):
#     def __init__(self,datasets, batch_size, num_user, num_item, dim_id, aggr_mode, num_layer, has_feature, dropout,
#                  dim_latent=None,device = None,features=None, user_profile=None):
#         super(GCN, self).__init__()
#         self.batch_size = batch_size
#         self.num_user = num_user
#         self.num_item = num_item
#         self.datasets = datasets
#         self.dim_id = dim_id
#         self.dim_feat = features.size(1)
#         self.dim_latent = dim_latent
#         self.aggr_mode = aggr_mode
#         self.has_feature = has_feature
#         self.dropout = dropout
#         self.device = device
#         self.userprofile = user_profile

#         if self.has_feature:
#             self.preference = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
#                 np.random.randn(num_user, self.dim_latent), dtype=torch.float32, requires_grad=True),
#                 gain=1))
#             self.conv_embed_1 = Base_gcn(self.dim_latent, self.dim_latent, aggr=self.aggr_mode)
#         else:
#             self.preference = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
#                 np.random.randn(num_user, self.dim_feat), dtype=torch.float32, requires_grad=True),
#                 gain=1))
#             self.conv_embed_1 = Base_gcn(self.dim_latent, self.dim_latent, aggr=self.aggr_mode)

#     def forward(self,edge_index,features, edge_mask = None):
#         temp_features = features
#         temp_profile = self.preference
#         x = torch.cat((temp_profile, temp_features), dim=0)
#         x = F.normalize(x)
#         h = self.conv_embed_1(x, edge_index,edge_mask)  # equation 1
#         h_1 = self.conv_embed_1(h, edge_index,edge_mask)  # equation 1
#         h_2 = self.conv_embed_1(h_1, edge_index,edge_mask)

#         x_hat =h + x + h_1 + h_2
#         return x_hat, self.preference


# class Base_gcn(MessagePassing):
#     def __init__(self, in_channels, out_channels, normalize=True, bias=True, aggr='add', **kwargs):
#         super(Base_gcn, self).__init__(aggr=aggr, **kwargs)
#         self.aggr = aggr
#         self.in_channels = in_channels
#         self.out_channels = out_channels

#     def forward(self, x, edge_index,edge_mask=None, size=None):
#         # pdb.set_trace()

#         if edge_mask is None:
#             edge_mask = torch.ones(
#                 edge_index.size(1),
#                 device=x.device,
#                 dtype=x.dtype
#             )

#         if size is None:
#             edge_index, _ = remove_self_loops(edge_index)
#             # edge_index, _ = add_self_loops(edge_index, num_nodes=x.size(0))
#         x = x.unsqueeze(-1) if x.dim() == 1 else x
#         # pdb.set_trace()
#         return self.propagate(edge_index, size=(x.size(0), x.size(0)), x=x, edge_mask = edge_mask)

#     def message(self, x_j, edge_index, size,edge_mask):
#         if self.aggr == 'add':
#             # pdb.set_trace()
#             row, col = edge_index
#             deg = degree(row, size[0], dtype=x_j.dtype)
#             deg_inv_sqrt = deg.pow(-0.5)
#             deg_inv_sqrt[
#             torch.isinf(deg_inv_sqrt)
#             ] = 0

#             norm = deg_inv_sqrt[row] * deg_inv_sqrt[col]
#             # return norm.view(-1, 1) * x_j
#             return (
#                 norm.view(-1, 1)
#                 * edge_mask.view(-1, 1)
#                 * x_j
#             )
#         return x_j

#     def update(self, aggr_out):
#         return aggr_out

#     def __repr(self):
#         return '{}({},{})'.format(self.__class__.__name__, self.in_channels, self.out_channels)

# coding: utf-8
# 
#
# user-graph need to be generated by the following script
# tools/generate-u-u-matrix.py

##############################

import os
import numpy as np
import scipy.sparse as sp
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn.conv import MessagePassing
from torch_geometric.utils import remove_self_loops, add_self_loops, degree
import torch_geometric

from common.abstract_recommender import GeneralRecommender
from common.loss import BPRLoss, EmbLoss
from common.init import xavier_uniform_initialization
from torch.nn import MultiheadAttention
# from .transformer import TransformerEncoder

class MASKED_GLORIA_EX(GeneralRecommender):
    def __init__(self, config, dataset):
        super(MASKED_GLORIA_EX, self).__init__(config, dataset)

        num_user = self.n_users
        num_item = self.n_items
        print('number of users: {}, number of items: {}'.format(num_user, num_item))
        
        batch_size = config['train_batch_size']         # not used
        dim_x = config['embedding_size']
        self.feat_embed_dim = config['feat_embed_dim']
        self.n_layers = config['n_mm_layers']
        self.knn_k = config['knn_k']

        self.batch_size = batch_size
        self.num_user = num_user
        self.num_item = num_item
        self.k = 40
        self.aggr_mode = config['aggr_mode']
        self.user_aggr_mode = 'softmax'
        self.num_layer = 1
        self.dataset = dataset
        self.reg_weight = config['reg_weight']
        self.drop_rate = 0.1
        self.t_rep = None
        self.t_preference = None
        self.dim_latent = 64
        self.mm_adj = None
        self.config = config
        dataset_path = os.path.abspath(config['data_path'] + config['dataset'])
        
        mm_adj_file = os.path.join(dataset_path, 'mm_adj_{}.pt'.format(self.knn_k))

        # self.id_embedding_low = nn.Embedding(num_item, self.feat_embed_dim)
        # self.id_embedding_high = nn.Embedding(num_item, self.feat_embed_dim)
        self.id_embedding_full = nn.Embedding(num_item, self.feat_embed_dim)
        self.id_embedding_masked = nn.Embedding(num_item, self.feat_embed_dim)

        self.mlp_item = nn.Linear(self.t_feat.shape[-1], self.dim_latent, bias=False)
        self.mlp_user = nn.Linear(self.user_feat.shape[-1], self.dim_latent, bias=False)

        indices, text_adj = self.get_knn_adj_mat(self.t_feat)
        self.mm_adj = text_adj

        train_interactions = dataset.inter_matrix(form='coo').astype(np.float32)

        # ============================================================
        # Original user-item edges (one direction only)
        # ============================================================
        edge_index = self.pack_edge_index(train_interactions)
        self.num_interactions = edge_index.shape[0]

        # edge_user_ids[e] tells us which user owns original edge e.
        # Shape: [num_interactions]
        #
        # User-level scalar mask: 
        #     M_(u,i) = sigmoid(user_mask_logits[u])
        self.register_buffer(
            'edge_user_ids',
            torch.tensor(
                edge_index[:, 0],
                dtype=torch.long,
                device=self.device
            )
        )

        edge_index = torch.tensor(
            edge_index,
            dtype=torch.long,
            device=self.device
        ).t().contiguous()

        # Keep the same undirected interaction graph as the original code.
        self.edge_index = torch.cat(
            [edge_index, edge_index[[1, 0]]],
            dim=1
        )

        # ============================================================
        # USER-LEVEL LEARNABLE SCALAR MASK
        # ============================================================
        # Original:
        #     one learnable logit per interaction edge -> O(|E|)
        #
        # Here:
        #     one learnable logit per user -> O(|U|)
        #
        # All interaction edges of user u receive the same scalar:
        #     m_u = sigmoid(user_mask_logits[u])
        #
        # Initialize at zero so sigmoid(0)=0.5, matching the original
        # edge-level mask initialization for a clean ablation.
        self.user_mask_logits = nn.Parameter(
            torch.zeros(
                self.num_user,
                device=self.device
            )
        )

        edge_index = self.pack_edge_index(train_interactions)

        item_ids = edge_index[:, 1] - self.num_user
        item_degree = np.bincount(item_ids, minlength=self.num_item)

        high_ratio = 0.10
        num_high = int(self.num_item * high_ratio)

        high_items = np.argsort(item_degree)[-num_high:]
        high_items = set(high_items.tolist())

        low_edges = []
        high_edges = []

        for edge in edge_index:
            item_id = edge[1] - self.num_user

            if item_id in high_items:
                high_edges.append(edge)
            else:
                low_edges.append(edge)

        low_edges = np.array(low_edges, dtype=np.int64)
        high_edges = np.array(high_edges, dtype=np.int64)

        self.edge_index_low = torch.tensor(low_edges, dtype=torch.long).t().contiguous().to(self.device)
        self.edge_index_high = torch.tensor(high_edges, dtype=torch.long).t().contiguous().to(self.device)

        self.edge_index_low = torch.cat(
            (self.edge_index_low, self.edge_index_low[[1, 0]]),
            dim=1
        )

        self.edge_index_high = torch.cat(
            (self.edge_index_high, self.edge_index_high[[1, 0]]),
            dim=1
        )
        # self.edge = concat 2 edge_index to make the graph undirected
        # self.edge_index = torch.cat((self.edge_index_low, self.edge_index_high), dim=1)

        # self.idl_gcn = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
        #                 num_layer=self.num_layer, has_feature=False, dropout=self.drop_rate, dim_latent=64,
        #                 device=self.device, features=self.id_embedding.weight)
        # self.idh_gcn = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
        #                 num_layer=self.num_layer, has_feature=False, dropout=self.drop_rate, dim_latent=64,
        #                 device=self.device, features=self.id_embedding.weight)

        self.full_gcn = GCN(
                        self.dataset,
                        batch_size,
                        num_user,
                        num_item,
                        dim_x,
                        self.aggr_mode,
                        num_layer=self.num_layer,
                        has_feature=False,
                        dropout=self.drop_rate,
                        dim_latent=64,
                        device=self.device,
                        features=self.id_embedding_full.weight
                    )

        self.mask_gcn = GCN(
            self.dataset,
            batch_size,
            num_user,
            num_item,
            dim_x,
            self.aggr_mode,
            num_layer=self.num_layer,
            has_feature=False,
            dropout=self.drop_rate,
            dim_latent=64,
            device=self.device,
            features=self.id_embedding_masked.weight
        )
        if config['fusion'] in ['add', 'pool']:
            pass
        elif config['fusion'] == 'Multi-Head Attention':
            self.multihead_attn = nn.MultiheadAttention(embed_dim=64, num_heads=4)
        elif config['fusion'] == 'Transformer':
            self.transformer = TransformerEncoder(64, num_heads= 4, layers=2)
        else:
            raise NotImplementedError
        


    def get_knn_adj_mat(self, mm_embeddings):
        context_norm = mm_embeddings.div(torch.norm(mm_embeddings, p=2, dim=-1, keepdim=True))
        sim = torch.mm(context_norm, context_norm.transpose(1, 0))
        _, knn_ind = torch.topk(sim, self.knn_k, dim=-1)
        adj_size = sim.size()
        del sim
        # construct sparse adj
        indices0 = torch.arange(knn_ind.shape[0]).to(self.device)
        indices0 = torch.unsqueeze(indices0, 1)
        indices0 = indices0.expand(-1, self.knn_k)
        indices = torch.stack((torch.flatten(indices0), torch.flatten(knn_ind)), 0)
        # norm
        return indices, self.compute_normalized_laplacian(indices, adj_size)
    
    def compute_normalized_laplacian(self, indices, adj_size):
        adj = torch.sparse.FloatTensor(indices, torch.ones_like(indices[0]), adj_size)
        row_sum = 1e-7 + torch.sparse.sum(adj, -1).to_dense()
        r_inv_sqrt = torch.pow(row_sum, -0.5)
        rows_inv_sqrt = r_inv_sqrt[indices[0]]
        cols_inv_sqrt = r_inv_sqrt[indices[1]]
        values = rows_inv_sqrt * cols_inv_sqrt
        return torch.sparse.FloatTensor(indices, values, adj_size)

    def pack_edge_index(self, inter_mat):
        rows = inter_mat.row
        cols = inter_mat.col + self.n_users
        return np.column_stack((rows, cols))

    def item_item(self, rep):
        h = rep
        for i in range(self.n_layers):
            h = torch.sparse.mm(self.mm_adj, h)
        return rep + h

    def get_user_mask(self):
        """Return one learned scalar mask value for each user."""
        return torch.sigmoid(self.user_mask_logits)

    def get_original_edge_mask(self):
        """
        Expand user-level scalar masks to the original user-item edges.

        For original edge e=(u,i):
            edge_mask[e] = sigmoid(user_mask_logits[u])
        """
        user_mask = self.get_user_mask()
        return user_mask[self.edge_user_ids]

    @torch.no_grad()
    def get_user_mask_statistics(self):
        """Diagnostics for the learned user-level mask."""
        user_mask = self.get_user_mask().detach()
        return {
            'mean_keep': user_mask.mean().item(),
            'mean_attenuation': (1.0 - user_mask).mean().item(),
            'min_keep': user_mask.min().item(),
            'max_keep': user_mask.max().item(),
            'std_keep': user_mask.std(unbiased=False).item(),
        }

    def forward(self, interaction):
        user_nodes = interaction[0]
        pos_item_nodes = interaction[1] + self.n_users
        neg_item_nodes = interaction[2] + self.n_users

        # item_feat = self.mlp_item(self.t_feat)
        # user_feat = F.normalize(self.mlp_user(self.user_feat))
        
        # self.idl_rep, self.t_preference = self.idl_gcn(self.edge_index, self.id_embedding_low.weight)
        # self.idh_rep, self.id_preference = self.idh_gcn(self.edge_index, self.id_embedding_high.weight)

        self.full_rep, self.full_preference = self.full_gcn(
                                                self.edge_index,
                                                self.id_embedding_full.weight
                                            )

        # ============================================================
        # User-level scalar mask
        # ============================================================
        # user_mask: [num_user]
        # mask:      [num_interactions]
        #
        # Every interaction edge of the same user receives the same
        # learned scalar weight.
        user_mask = self.get_user_mask()
        mask = user_mask[self.edge_user_ids]

        # self.edge_index = original edges + reverse edges.
        # Use the same user-conditioned mask in both directions.
        edge_mask = torch.cat(
            [mask, mask],
            dim=0
        )

        self.mask_rep, self.mask_preference = self.mask_gcn(
                                                self.edge_index,
                                                self.id_embedding_masked.weight,
                                                edge_mask=edge_mask
                                            )

        item_repl = self.full_rep[self.num_user:]
        item_reph = self.mask_rep[self.num_user:]

        item_rep = torch.cat((item_repl, item_reph), dim=1)
        item_rep = self.item_item(item_rep)

        user_repl = self.full_rep[:self.num_user]
        user_reph = self.mask_rep[:self.num_user]

        user_rep = torch.cat((user_repl, user_reph), dim=1)

        self.result_embed = torch.cat((user_rep, item_rep), dim=0)
        user_tensor = self.result_embed[user_nodes]
        pos_item_tensor = self.result_embed[pos_item_nodes]
        neg_item_tensor = self.result_embed[neg_item_nodes]
        pos_scores = torch.sum(user_tensor * pos_item_tensor, dim=1)
        neg_scores = torch.sum(user_tensor * neg_item_tensor, dim=1)
        return pos_scores, neg_scores

    def calculate_loss(self, interaction):
        pos_scores, neg_scores = self.forward(interaction)
        loss_value = -torch.mean(torch.log2(torch.sigmoid(pos_scores - neg_scores)))
        return loss_value

    def full_sort_predict(self, interaction):
        user_tensor = self.result_embed[:self.n_users]
        item_tensor = self.result_embed[self.n_users:]

        temp_user_tensor = user_tensor[interaction[0], :]
        score_matrix = torch.matmul(temp_user_tensor, item_tensor.t())
        return score_matrix

class GCN(torch.nn.Module):
    def __init__(self,datasets, batch_size, num_user, num_item, dim_id, aggr_mode, num_layer, has_feature, dropout,
                 dim_latent=None,device = None,features=None, user_profile=None):
        super(GCN, self).__init__()
        self.batch_size = batch_size
        self.num_user = num_user
        self.num_item = num_item
        self.datasets = datasets
        self.dim_id = dim_id
        self.dim_feat = features.size(1)
        self.dim_latent = dim_latent
        self.aggr_mode = aggr_mode
        self.has_feature = has_feature
        self.dropout = dropout
        self.device = device
        self.userprofile = user_profile

        if self.has_feature:
            self.preference = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
                np.random.randn(num_user, self.dim_latent), dtype=torch.float32, requires_grad=True),
                gain=1))
            self.conv_embed_1 = Base_gcn(self.dim_latent, self.dim_latent, aggr=self.aggr_mode)
        else:
            self.preference = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
                np.random.randn(num_user, self.dim_feat), dtype=torch.float32, requires_grad=True),
                gain=1))
            self.conv_embed_1 = Base_gcn(self.dim_latent, self.dim_latent, aggr=self.aggr_mode)

    def forward(self,edge_index,features, edge_mask = None):
        temp_features = features
        temp_profile = self.preference
        x = torch.cat((temp_profile, temp_features), dim=0)
        x = F.normalize(x)
        h = self.conv_embed_1(x, edge_index,edge_mask)  # equation 1
        h_1 = self.conv_embed_1(h, edge_index,edge_mask)  # equation 1
        h_2 = self.conv_embed_1(h_1, edge_index,edge_mask)

        x_hat =h + x + h_1 + h_2
        return x_hat, self.preference


class Base_gcn(MessagePassing):
    def __init__(self, in_channels, out_channels, normalize=True, bias=True, aggr='add', **kwargs):
        super(Base_gcn, self).__init__(aggr=aggr, **kwargs)
        self.aggr = aggr
        self.in_channels = in_channels
        self.out_channels = out_channels

    def forward(self, x, edge_index,edge_mask=None, size=None):
        # pdb.set_trace()

        if edge_mask is None:
            edge_mask = torch.ones(
                edge_index.size(1),
                device=x.device,
                dtype=x.dtype
            )

        if size is None:
            edge_index, _ = remove_self_loops(edge_index)
            # edge_index, _ = add_self_loops(edge_index, num_nodes=x.size(0))
        x = x.unsqueeze(-1) if x.dim() == 1 else x
        # pdb.set_trace()
        return self.propagate(edge_index, size=(x.size(0), x.size(0)), x=x, edge_mask = edge_mask)

    def message(self, x_j, edge_index, size,edge_mask):
        if self.aggr == 'add':
            # pdb.set_trace()
            row, col = edge_index
            deg = degree(row, size[0], dtype=x_j.dtype)
            deg_inv_sqrt = deg.pow(-0.5)
            deg_inv_sqrt[
            torch.isinf(deg_inv_sqrt)
            ] = 0

            norm = deg_inv_sqrt[row] * deg_inv_sqrt[col]
            # return norm.view(-1, 1) * x_j
            return (
                norm.view(-1, 1)
                * edge_mask.view(-1, 1)
                * x_j
            )
        return x_j

    def update(self, aggr_out):
        return aggr_out

    def __repr(self):
        return '{}({},{})'.format(self.__class__.__name__, self.in_channels, self.out_channels)

######################################################

# import os
# import numpy as np
# import scipy.sparse as sp
# import torch
# import torch.nn as nn
# import torch.nn.functional as F
# from torch_geometric.nn.conv import MessagePassing
# from torch_geometric.utils import remove_self_loops, add_self_loops, degree
# import torch_geometric

# from common.abstract_recommender import GeneralRecommender
# from common.loss import BPRLoss, EmbLoss
# from common.init import xavier_uniform_initialization
# from torch.nn import MultiheadAttention
# # from .transformer import TransformerEncoder

# class MASKED_GLORIA_EX(GeneralRecommender):
#     def __init__(self, config, dataset):
#         super(MASKED_GLORIA_EX, self).__init__(config, dataset)

#         num_user = self.n_users
#         num_item = self.n_items
#         print('number of users: {}, number of items: {}'.format(num_user, num_item))
        
#         batch_size = config['train_batch_size']         # not used
#         dim_x = config['embedding_size']
#         self.feat_embed_dim = config['feat_embed_dim']
#         self.n_layers = config['n_mm_layers']
#         self.knn_k = config['knn_k']

#         self.batch_size = batch_size
#         self.num_user = num_user
#         self.num_item = num_item
#         self.k = 40
#         self.aggr_mode = config['aggr_mode']
#         self.user_aggr_mode = 'softmax'
#         self.num_layer = 1
#         self.dataset = dataset
#         self.reg_weight = config['reg_weight']
#         self.drop_rate = 0.1
#         self.t_rep = None
#         self.t_preference = None
#         self.dim_latent = 64
#         self.mm_adj = None
#         self.config = config
#         dataset_path = os.path.abspath(config['data_path'] + config['dataset'])
        
#         mm_adj_file = os.path.join(dataset_path, 'mm_adj_{}.pt'.format(self.knn_k))

#         # self.id_embedding_low = nn.Embedding(num_item, self.feat_embed_dim)
#         # self.id_embedding_high = nn.Embedding(num_item, self.feat_embed_dim)
#         self.id_embedding_full = nn.Embedding(num_item, self.feat_embed_dim)
#         self.id_embedding_masked = nn.Embedding(num_item, self.feat_embed_dim)

#         self.mlp_item = nn.Linear(self.t_feat.shape[-1], self.dim_latent, bias=False)
#         self.mlp_user = nn.Linear(self.user_feat.shape[-1], self.dim_latent, bias=False)

#         indices, text_adj = self.get_knn_adj_mat(self.t_feat)
#         self.mm_adj = text_adj

#         train_interactions = dataset.inter_matrix(form='coo').astype(np.float32)

#         # ============================================================
#         # Original user-item edges (one direction only)
#         # ============================================================
#         edge_index = self.pack_edge_index(train_interactions)
#         self.num_interactions = edge_index.shape[0]

#         # edge_user_ids[e] tells us which user owns original edge e.
#         # Shape: [num_interactions]
#         #
#         # User-level scalar mask:
#         #     M_(u,i) = sigmoid(user_mask_logits[u])
#         self.register_buffer(
#             'edge_user_ids',
#             torch.tensor(
#                 edge_index[:, 0],
#                 dtype=torch.long,
#                 device=self.device
#             )
#         )

#         edge_index = torch.tensor(
#             edge_index,
#             dtype=torch.long,
#             device=self.device
#         ).t().contiguous()

#         # Keep the same undirected interaction graph as the original code.
#         self.edge_index = torch.cat(
#             [edge_index, edge_index[[1, 0]]],
#             dim=1
#         )

#         # ============================================================
#         # USER-LEVEL LEARNABLE SCALAR MASK
#         # ============================================================
#         # Original:
#         #     one learnable logit per interaction edge -> O(|E|)
#         #
#         # Here:
#         #     one learnable logit per user -> O(|U|)
#         #
#         # All interaction edges of user u receive the same scalar:
#         #     m_u = sigmoid(user_mask_logits[u])
#         #
#         # Initialize at zero so sigmoid(0)=0.5, matching the original
#         # edge-level mask initialization for a clean ablation.
#         self.user_mask_logits = nn.Parameter(
#             torch.zeros(
#                 self.num_user,
#                 device=self.device
#             )
#         )

#         # ============================================================
#         # STOCHASTIC COUNTERFACTUAL NEIGHBORHOOD INTERVENTION
#         # ============================================================
#         # Deterministic learned user-level neighborhood strength:
#         #     m_u = sigmoid(user_mask_logits[u])
#         #
#         # During TRAINING only, sample one local counterfactual world:
#         #     m_tilde_u = clip(m_u + eps_u, 0, 1)
#         #     eps_u ~ Uniform(-cf_delta, +cf_delta)
#         #
#         # During VALIDATION / TEST:
#         #     m_tilde_u = m_u
#         #
#         # Setting cf_delta = 0.0 exactly recovers the deterministic
#         # Full + User Scalar Mask baseline.
#         self.cf_delta = float(0.10)

#         # Optional probability of applying the stochastic intervention
#         # on a training forward pass. Keep 1.0 for the main experiment.
#         self.cf_apply_prob = float(1.0)

#         # Store diagnostics from the most recent forward pass.
#         self.last_base_user_mask = None
#         self.last_sampled_user_mask = None
#         self.last_cf_noise = None

#         # Deterministic evaluation embedding cache.
#         self._deterministic_eval_cache_valid = False

#         edge_index = self.pack_edge_index(train_interactions)

#         item_ids = edge_index[:, 1] - self.num_user
#         item_degree = np.bincount(item_ids, minlength=self.num_item)

#         high_ratio = 0.10
#         num_high = int(self.num_item * high_ratio)

#         high_items = np.argsort(item_degree)[-num_high:]
#         high_items = set(high_items.tolist())

#         low_edges = []
#         high_edges = []

#         for edge in edge_index:
#             item_id = edge[1] - self.num_user

#             if item_id in high_items:
#                 high_edges.append(edge)
#             else:
#                 low_edges.append(edge)

#         low_edges = np.array(low_edges, dtype=np.int64)
#         high_edges = np.array(high_edges, dtype=np.int64)

#         self.edge_index_low = torch.tensor(low_edges, dtype=torch.long).t().contiguous().to(self.device)
#         self.edge_index_high = torch.tensor(high_edges, dtype=torch.long).t().contiguous().to(self.device)

#         self.edge_index_low = torch.cat(
#             (self.edge_index_low, self.edge_index_low[[1, 0]]),
#             dim=1
#         )

#         self.edge_index_high = torch.cat(
#             (self.edge_index_high, self.edge_index_high[[1, 0]]),
#             dim=1
#         )
#         # self.edge = concat 2 edge_index to make the graph undirected
#         # self.edge_index = torch.cat((self.edge_index_low, self.edge_index_high), dim=1)

#         # self.idl_gcn = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
#         #                 num_layer=self.num_layer, has_feature=False, dropout=self.drop_rate, dim_latent=64,
#         #                 device=self.device, features=self.id_embedding.weight)
#         # self.idh_gcn = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
#         #                 num_layer=self.num_layer, has_feature=False, dropout=self.drop_rate, dim_latent=64,
#         #                 device=self.device, features=self.id_embedding.weight)

#         self.full_gcn = GCN(
#                         self.dataset,
#                         batch_size,
#                         num_user,
#                         num_item,
#                         dim_x,
#                         self.aggr_mode,
#                         num_layer=self.num_layer,
#                         has_feature=False,
#                         dropout=self.drop_rate,
#                         dim_latent=64,
#                         device=self.device,
#                         features=self.id_embedding_full.weight
#                     )

#         self.mask_gcn = GCN(
#             self.dataset,
#             batch_size,
#             num_user,
#             num_item,
#             dim_x,
#             self.aggr_mode,
#             num_layer=self.num_layer,
#             has_feature=False,
#             dropout=self.drop_rate,
#             dim_latent=64,
#             device=self.device,
#             features=self.id_embedding_masked.weight
#         )
#         if config['fusion'] in ['add', 'pool']:
#             pass
#         elif config['fusion'] == 'Multi-Head Attention':
#             self.multihead_attn = nn.MultiheadAttention(embed_dim=64, num_heads=4)
#         elif config['fusion'] == 'Transformer':
#             self.transformer = TransformerEncoder(64, num_heads= 4, layers=2)
#         else:
#             raise NotImplementedError
        


#     def get_knn_adj_mat(self, mm_embeddings):
#         context_norm = mm_embeddings.div(torch.norm(mm_embeddings, p=2, dim=-1, keepdim=True))
#         sim = torch.mm(context_norm, context_norm.transpose(1, 0))
#         _, knn_ind = torch.topk(sim, self.knn_k, dim=-1)
#         adj_size = sim.size()
#         del sim
#         # construct sparse adj
#         indices0 = torch.arange(knn_ind.shape[0]).to(self.device)
#         indices0 = torch.unsqueeze(indices0, 1)
#         indices0 = indices0.expand(-1, self.knn_k)
#         indices = torch.stack((torch.flatten(indices0), torch.flatten(knn_ind)), 0)
#         # norm
#         return indices, self.compute_normalized_laplacian(indices, adj_size)
    
#     def compute_normalized_laplacian(self, indices, adj_size):
#         adj = torch.sparse.FloatTensor(indices, torch.ones_like(indices[0]), adj_size)
#         row_sum = 1e-7 + torch.sparse.sum(adj, -1).to_dense()
#         r_inv_sqrt = torch.pow(row_sum, -0.5)
#         rows_inv_sqrt = r_inv_sqrt[indices[0]]
#         cols_inv_sqrt = r_inv_sqrt[indices[1]]
#         values = rows_inv_sqrt * cols_inv_sqrt
#         return torch.sparse.FloatTensor(indices, values, adj_size)

#     def pack_edge_index(self, inter_mat):
#         rows = inter_mat.row
#         cols = inter_mat.col + self.n_users
#         return np.column_stack((rows, cols))

#     def item_item(self, rep):
#         h = rep
#         for i in range(self.n_layers):
#             h = torch.sparse.mm(self.mm_adj, h)
#         return rep + h

#     def get_user_mask(self):
#         """
#         Deterministic learned user-level neighborhood strength.

#         Returns:
#             Tensor [num_user] with values in (0, 1).

#         This is the mask used at validation/test time.
#         """
#         return torch.sigmoid(self.user_mask_logits)

#     def get_training_user_mask(self):
#         """
#         Sample ONE stochastic counterfactual neighborhood-strength world.

#         Base factual/user-specific strength:
#             m_u = sigmoid(theta_u)

#         Training counterfactual:
#             m_tilde_u = clip(m_u + eps_u, 0, 1)
#             eps_u ~ Uniform(-cf_delta, +cf_delta)

#         Validation/test:
#             m_tilde_u = m_u

#         Important:
#             The noise is NOT detached from m_u. Gradients still flow
#             through m_u into user_mask_logits via the standard BPR loss.
#             The random noise itself has no learnable parameters.
#         """
#         base_user_mask = self.get_user_mask()

#         # Deterministic behavior for validation/test or delta=0.
#         if (
#             (not self.training)
#             or self.cf_delta <= 0.0
#             or self.cf_apply_prob <= 0.0
#         ):
#             sampled_user_mask = base_user_mask
#             noise = torch.zeros_like(base_user_mask)

#         else:
#             # Optionally skip the intervention for the whole graph on
#             # some steps. For the main experiment use cf_apply_prob=1.
#             apply_cf = True
#             if self.cf_apply_prob < 1.0:
#                 apply_cf = (
#                     torch.rand(
#                         (),
#                         device=base_user_mask.device
#                     ).item()
#                     < self.cf_apply_prob
#                 )

#             if apply_cf:
#                 noise = (
#                     2.0 * torch.rand_like(base_user_mask)
#                     - 1.0
#                 ) * self.cf_delta

#                 sampled_user_mask = torch.clamp(
#                     base_user_mask + noise,
#                     min=0.0,
#                     max=1.0
#                 )
#             else:
#                 noise = torch.zeros_like(base_user_mask)
#                 sampled_user_mask = base_user_mask

#         # Diagnostics only. Detach so these do not hold computation graphs.
#         self.last_base_user_mask = base_user_mask.detach()
#         self.last_sampled_user_mask = sampled_user_mask.detach()
#         self.last_cf_noise = noise.detach()

#         return sampled_user_mask

#     def get_original_edge_mask(self, user_mask=None):
#         """
#         Expand user-level scalar masks to the original user-item edges.

#         For original edge e=(u,i):
#             edge_mask[e] = user_mask[u]

#         If user_mask is omitted, use the deterministic learned mask.
#         """
#         if user_mask is None:
#             user_mask = self.get_user_mask()

#         return user_mask[self.edge_user_ids]

#     @torch.no_grad()
#     def get_user_mask_statistics(self):
#         """Diagnostics for the deterministic learned user-level mask."""
#         user_mask = self.get_user_mask().detach()

#         return {
#             'mean_keep': user_mask.mean().item(),
#             'mean_attenuation': (1.0 - user_mask).mean().item(),
#             'min_keep': user_mask.min().item(),
#             'max_keep': user_mask.max().item(),
#             'std_keep': user_mask.std(unbiased=False).item(),
#         }

#     @torch.no_grad()
#     def get_counterfactual_statistics(self):
#         """
#         Diagnostics for the most recently sampled training world.
#         """
#         if (
#             self.last_base_user_mask is None
#             or self.last_sampled_user_mask is None
#         ):
#             return {}

#         base = self.last_base_user_mask
#         sampled = self.last_sampled_user_mask
#         difference = sampled - base

#         return {
#             'cf_delta': float(self.cf_delta),
#             'mean_base_keep': base.mean().item(),
#             'mean_sampled_keep': sampled.mean().item(),
#             'mean_abs_intervention': difference.abs().mean().item(),
#             'mean_signed_intervention': difference.mean().item(),
#             'fraction_more_compressed': (difference < 0).float().mean().item(),
#             'fraction_less_compressed': (difference > 0).float().mean().item(),
#             'fraction_unchanged': (difference == 0).float().mean().item(),
#             'sampled_min_keep': sampled.min().item(),
#             'sampled_max_keep': sampled.max().item(),
#         }

#     def forward(self, interaction):
#         if self.training:
#             # Parameters may be updated after this training forward, so
#             # any deterministic evaluation cache must be considered stale.
#             self._deterministic_eval_cache_valid = False

#         user_nodes = interaction[0]
#         pos_item_nodes = interaction[1] + self.n_users
#         neg_item_nodes = interaction[2] + self.n_users

#         # item_feat = self.mlp_item(self.t_feat)
#         # user_feat = F.normalize(self.mlp_user(self.user_feat))
        
#         # self.idl_rep, self.t_preference = self.idl_gcn(self.edge_index, self.id_embedding_low.weight)
#         # self.idh_rep, self.id_preference = self.idh_gcn(self.edge_index, self.id_embedding_high.weight)

#         self.full_rep, self.full_preference = self.full_gcn(
#                                                 self.edge_index,
#                                                 self.id_embedding_full.weight
#                                             )

#         # ============================================================
#         # User-level scalar mask
#         # ============================================================
#         # user_mask: [num_user]
#         # mask:      [num_interactions]
#         #
#         # Every interaction edge of the same user receives the same
#         # learned scalar weight.
#         # During training this samples one stochastic local
#         # counterfactual neighborhood-strength world.
#         #
#         # During validation/test get_training_user_mask() automatically
#         # returns the deterministic learned user mask.
#         user_mask = self.get_training_user_mask()
#         mask = user_mask[self.edge_user_ids]

#         # self.edge_index = original edges + reverse edges.
#         # Use the same user-conditioned mask in both directions.
#         edge_mask = torch.cat(
#             [mask, mask],
#             dim=0
#         )

#         self.mask_rep, self.mask_preference = self.mask_gcn(
#                                                 self.edge_index,
#                                                 self.id_embedding_masked.weight,
#                                                 edge_mask=edge_mask
#                                             )

#         item_repl = self.full_rep[self.num_user:]
#         item_reph = self.mask_rep[self.num_user:]

#         item_rep = torch.cat((item_repl, item_reph), dim=1)
#         item_rep = self.item_item(item_rep)

#         user_repl = self.full_rep[:self.num_user]
#         user_reph = self.mask_rep[:self.num_user]

#         user_rep = torch.cat((user_repl, user_reph), dim=1)

#         self.result_embed = torch.cat((user_rep, item_rep), dim=0)
#         user_tensor = self.result_embed[user_nodes]
#         pos_item_tensor = self.result_embed[pos_item_nodes]
#         neg_item_tensor = self.result_embed[neg_item_nodes]
#         pos_scores = torch.sum(user_tensor * pos_item_tensor, dim=1)
#         neg_scores = torch.sum(user_tensor * neg_item_tensor, dim=1)
#         return pos_scores, neg_scores

#     def calculate_loss(self, interaction):
#         pos_scores, neg_scores = self.forward(interaction)
#         loss_value = -torch.mean(torch.log2(torch.sigmoid(pos_scores - neg_scores)))
#         return loss_value

#     @torch.no_grad()
#     def recompute_deterministic_result_embedding(self):
#         """
#         Recompute result embeddings with the deterministic learned
#         user mask. Useful before validation/test if the trainer does not
#         automatically call forward() in eval mode.
#         """
#         full_rep, _ = self.full_gcn(
#             self.edge_index,
#             self.id_embedding_full.weight
#         )

#         deterministic_user_mask = self.get_user_mask()
#         deterministic_edge_mask = self.get_original_edge_mask(
#             deterministic_user_mask
#         )
#         deterministic_edge_mask = torch.cat(
#             [deterministic_edge_mask, deterministic_edge_mask],
#             dim=0
#         )

#         mask_rep, _ = self.mask_gcn(
#             self.edge_index,
#             self.id_embedding_masked.weight,
#             edge_mask=deterministic_edge_mask
#         )

#         item_full = full_rep[self.num_user:]
#         item_mask = mask_rep[self.num_user:]

#         item_rep = torch.cat(
#             (item_full, item_mask),
#             dim=1
#         )
#         item_rep = self.item_item(item_rep)

#         user_full = full_rep[:self.num_user]
#         user_mask_rep = mask_rep[:self.num_user]

#         user_rep = torch.cat(
#             (user_full, user_mask_rep),
#             dim=1
#         )

#         self.full_rep = full_rep
#         self.mask_rep = mask_rep
#         self.result_embed = torch.cat(
#             (user_rep, item_rep),
#             dim=0
#         )

#         self._deterministic_eval_cache_valid = True
#         return self.result_embed

#     def full_sort_predict(self, interaction):
#         # Training uses stochastic counterfactual masks, but ranking
#         # evaluation should always use the learned deterministic mask.
#         #
#         # Recompute once after the latest training phase, then reuse the
#         # deterministic cache for the remaining evaluation batches.
#         if not self._deterministic_eval_cache_valid:
#             self.recompute_deterministic_result_embedding()
#         user_tensor = self.result_embed[:self.n_users]
#         item_tensor = self.result_embed[self.n_users:]

#         temp_user_tensor = user_tensor[interaction[0], :]
#         score_matrix = torch.matmul(temp_user_tensor, item_tensor.t())
#         return score_matrix

# class GCN(torch.nn.Module):
#     def __init__(self,datasets, batch_size, num_user, num_item, dim_id, aggr_mode, num_layer, has_feature, dropout,
#                  dim_latent=None,device = None,features=None, user_profile=None):
#         super(GCN, self).__init__()
#         self.batch_size = batch_size
#         self.num_user = num_user
#         self.num_item = num_item
#         self.datasets = datasets
#         self.dim_id = dim_id
#         self.dim_feat = features.size(1)
#         self.dim_latent = dim_latent
#         self.aggr_mode = aggr_mode
#         self.has_feature = has_feature
#         self.dropout = dropout
#         self.device = device
#         self.userprofile = user_profile

#         if self.has_feature:
#             self.preference = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
#                 np.random.randn(num_user, self.dim_latent), dtype=torch.float32, requires_grad=True),
#                 gain=1))
#             self.conv_embed_1 = Base_gcn(self.dim_latent, self.dim_latent, aggr=self.aggr_mode)
#         else:
#             self.preference = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
#                 np.random.randn(num_user, self.dim_feat), dtype=torch.float32, requires_grad=True),
#                 gain=1))
#             self.conv_embed_1 = Base_gcn(self.dim_latent, self.dim_latent, aggr=self.aggr_mode)

#     def forward(self,edge_index,features, edge_mask = None):
#         temp_features = features
#         temp_profile = self.preference
#         x = torch.cat((temp_profile, temp_features), dim=0)
#         x = F.normalize(x)
#         h = self.conv_embed_1(x, edge_index,edge_mask)  # equation 1
#         h_1 = self.conv_embed_1(h, edge_index,edge_mask)  # equation 1
#         h_2 = self.conv_embed_1(h_1, edge_index,edge_mask)

#         x_hat =h + x + h_1 + h_2
#         return x_hat, self.preference


# class Base_gcn(MessagePassing):
#     def __init__(self, in_channels, out_channels, normalize=True, bias=True, aggr='add', **kwargs):
#         super(Base_gcn, self).__init__(aggr=aggr, **kwargs)
#         self.aggr = aggr
#         self.in_channels = in_channels
#         self.out_channels = out_channels

#     def forward(self, x, edge_index,edge_mask=None, size=None):
#         # pdb.set_trace()

#         if edge_mask is None:
#             edge_mask = torch.ones(
#                 edge_index.size(1),
#                 device=x.device,
#                 dtype=x.dtype
#             )

#         if size is None:
#             edge_index, _ = remove_self_loops(edge_index)
#             # edge_index, _ = add_self_loops(edge_index, num_nodes=x.size(0))
#         x = x.unsqueeze(-1) if x.dim() == 1 else x
#         # pdb.set_trace()
#         return self.propagate(edge_index, size=(x.size(0), x.size(0)), x=x, edge_mask = edge_mask)

#     def message(self, x_j, edge_index, size,edge_mask):
#         if self.aggr == 'add':
#             # pdb.set_trace()
#             row, col = edge_index
#             deg = degree(row, size[0], dtype=x_j.dtype)
#             deg_inv_sqrt = deg.pow(-0.5)
#             deg_inv_sqrt[
#             torch.isinf(deg_inv_sqrt)
#             ] = 0

#             norm = deg_inv_sqrt[row] * deg_inv_sqrt[col]
#             # return norm.view(-1, 1) * x_j
#             return (
#                 norm.view(-1, 1)
#                 * edge_mask.view(-1, 1)
#                 * x_j
#             )
#         return x_j

#     def update(self, aggr_out):
#         return aggr_out

#     def __repr(self):
#         return '{}({},{})'.format(self.__class__.__name__, self.in_channels, self.out_channels)