# coding: utf-8
# 
#
# user-graph need to be generated by the following script
# tools/generate-u-u-matrix.py
import os
import numpy as np
import scipy.sparse as sp
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn.conv import MessagePassing
from torch_geometric.utils import remove_self_loops, add_self_loops, degree
import torch_geometric

from common.abstract_recommender import GeneralRecommender
from common.loss import BPRLoss, EmbLoss
from common.init import xavier_uniform_initialization
from torch.nn import MultiheadAttention
# from .transformer import TransformerEncoder

class MASKED_GLORIA_MIPD(GeneralRecommender):
    def __init__(self, config, dataset):
        super(MASKED_GLORIA_MIPD, self).__init__(config, dataset)

        num_user = self.n_users
        num_item = self.n_items
        print('number of users: {}, number of items: {}'.format(num_user, num_item))
        
        batch_size = config['train_batch_size']         # not used
        dim_x = config['embedding_size']
        self.feat_embed_dim = config['feat_embed_dim']
        self.n_layers = config['n_mm_layers']
        self.knn_k = config['knn_k']

        self.batch_size = batch_size
        self.num_user = num_user
        self.num_item = num_item
        self.k = 40
        self.aggr_mode = config['aggr_mode']
        self.user_aggr_mode = 'softmax'
        self.num_layer = 1
        self.dataset = dataset
        self.reg_weight = config['reg_weight']
        # MIPD (Mutual Information Perturbed Difference) regularizer.
        # Defaults keep the feature active without requiring changes in old
        # configuration files.  Set mipd_weight to 0.0 to disable it.
        self.mipd_weight = float(
            self._get_config_value(config, 'mipd_weight', 0.5)
        )
        self.mipd_num_samples = int(
            self._get_config_value(config, 'mipd_num_samples', 30)
        )
        self.mipd_temperature = float(
            self._get_config_value(config, 'mipd_temperature', 1.0)
        )
        if self.mipd_weight < 0.0:
            raise ValueError('mipd_weight must be non-negative.')
        if self.mipd_num_samples < 1:
            raise ValueError('mipd_num_samples must be at least 1.')
        if self.mipd_temperature <= 0.0:
            raise ValueError('mipd_temperature must be positive.')

        # Latest detached values are useful for logging without changing the
        # calculate_loss return type expected by the existing trainer.
        self.last_ranking_loss = None
        self.last_mipd_loss = None
        self.last_mipd_jsd = None
        self.drop_rate = 0.1
        self.t_rep = None
        self.t_preference = None
        self.dim_latent = 64
        self.mm_adj = None
        self.config = config
        dataset_path = os.path.abspath(config['data_path'] + config['dataset'])
        
        mm_adj_file = os.path.join(dataset_path, 'mm_adj_{}.pt'.format(self.knn_k))

        # self.id_embedding_low = nn.Embedding(num_item, self.feat_embed_dim)
        # self.id_embedding_high = nn.Embedding(num_item, self.feat_embed_dim)
        self.id_embedding_full = nn.Embedding(num_item, self.feat_embed_dim)
        self.id_embedding_masked = nn.Embedding(num_item, self.feat_embed_dim)

        self.mlp_item = nn.Linear(self.t_feat.shape[-1], self.dim_latent, bias=False)
        self.mlp_user = nn.Linear(self.user_feat.shape[-1], self.dim_latent, bias=False)

        indices, text_adj = self.get_knn_adj_mat(self.t_feat)
        self.mm_adj = text_adj

        train_interactions = dataset.inter_matrix(form='coo').astype(np.float32)

        edge_index = self.pack_edge_index(train_interactions)

        self.num_interactions = edge_index.shape[0]

        edge_index = torch.tensor(edge_index,
                                  dtype=torch.long,
                                  device=self.device).t().contiguous()

        # Keep the forward interaction ordering used by mask_logits.  These are
        # runtime tensors (not persistent buffers), so adding them does not
        # change the model state_dict or invalidate existing checkpoints.
        self.forward_edge_index = edge_index
        self.forward_edge_users = edge_index[0]
        self.forward_edge_items = edge_index[1] - self.num_user

        self.edge_index = torch.cat(
                            [edge_index, edge_index[[1, 0]]],
                            dim=1
                        )

        self.mask_logits = nn.Parameter(
                            torch.zeros(
                                self.num_interactions,
                                device=self.device
                            )
                        )

        edge_index = self.pack_edge_index(train_interactions)

        item_ids = edge_index[:, 1] - self.num_user
        item_degree = np.bincount(item_ids, minlength=self.num_item)

        high_ratio = 0.10
        num_high = int(self.num_item * high_ratio)

        high_items = np.argsort(item_degree)[-num_high:]
        high_items = set(high_items.tolist())

        low_edges = []
        high_edges = []

        for edge in edge_index:
            item_id = edge[1] - self.num_user

            if item_id in high_items:
                high_edges.append(edge)
            else:
                low_edges.append(edge)

        low_edges = np.array(low_edges, dtype=np.int64)
        high_edges = np.array(high_edges, dtype=np.int64)

        self.edge_index_low = torch.tensor(low_edges, dtype=torch.long).t().contiguous().to(self.device)
        self.edge_index_high = torch.tensor(high_edges, dtype=torch.long).t().contiguous().to(self.device)

        self.edge_index_low = torch.cat(
            (self.edge_index_low, self.edge_index_low[[1, 0]]),
            dim=1
        )

        self.edge_index_high = torch.cat(
            (self.edge_index_high, self.edge_index_high[[1, 0]]),
            dim=1
        )
        # self.edge = concat 2 edge_index to make the graph undirected
        # self.edge_index = torch.cat((self.edge_index_low, self.edge_index_high), dim=1)

        # self.idl_gcn = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
        #                 num_layer=self.num_layer, has_feature=False, dropout=self.drop_rate, dim_latent=64,
        #                 device=self.device, features=self.id_embedding.weight)
        # self.idh_gcn = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
        #                 num_layer=self.num_layer, has_feature=False, dropout=self.drop_rate, dim_latent=64,
        #                 device=self.device, features=self.id_embedding.weight)

        self.full_gcn = GCN(
                        self.dataset,
                        batch_size,
                        num_user,
                        num_item,
                        dim_x,
                        self.aggr_mode,
                        num_layer=self.num_layer,
                        has_feature=False,
                        dropout=self.drop_rate,
                        dim_latent=64,
                        device=self.device,
                        features=self.id_embedding_full.weight
                    )

        self.mask_gcn = GCN(
            self.dataset,
            batch_size,
            num_user,
            num_item,
            dim_x,
            self.aggr_mode,
            num_layer=self.num_layer,
            has_feature=False,
            dropout=self.drop_rate,
            dim_latent=64,
            device=self.device,
            features=self.id_embedding_masked.weight
        )
        # Fusion is a model-level default; the generic launcher does not
        # inject method-specific options.
        fusion = config['fusion'] or 'add'
        if fusion in ['add', 'pool']:
            pass
        elif fusion == 'Multi-Head Attention':
            self.multihead_attn = nn.MultiheadAttention(embed_dim=64, num_heads=4)
        elif fusion == 'Transformer':
            self.transformer = TransformerEncoder(64, num_heads= 4, layers=2)
        else:
            raise NotImplementedError


    @staticmethod
    def _get_config_value(config, key, default):
        """Read an optional config value while supporting dict-like configs."""
        try:
            value = config[key]
        except (KeyError, TypeError):
            return default
        return default if value is None else value


    def get_knn_adj_mat(self, mm_embeddings):
        context_norm = mm_embeddings.div(torch.norm(mm_embeddings, p=2, dim=-1, keepdim=True))
        sim = torch.mm(context_norm, context_norm.transpose(1, 0))
        _, knn_ind = torch.topk(sim, self.knn_k, dim=-1)
        adj_size = sim.size()
        del sim
        # construct sparse adj
        indices0 = torch.arange(knn_ind.shape[0]).to(self.device)
        indices0 = torch.unsqueeze(indices0, 1)
        indices0 = indices0.expand(-1, self.knn_k)
        indices = torch.stack((torch.flatten(indices0), torch.flatten(knn_ind)), 0)
        # norm
        return indices, self.compute_normalized_laplacian(indices, adj_size)
    
    def compute_normalized_laplacian(self, indices, adj_size):
        adj = torch.sparse.FloatTensor(indices, torch.ones_like(indices[0]), adj_size)
        row_sum = 1e-7 + torch.sparse.sum(adj, -1).to_dense()
        r_inv_sqrt = torch.pow(row_sum, -0.5)
        rows_inv_sqrt = r_inv_sqrt[indices[0]]
        cols_inv_sqrt = r_inv_sqrt[indices[1]]
        values = rows_inv_sqrt * cols_inv_sqrt
        return torch.sparse.FloatTensor(indices, values, adj_size)

    def pack_edge_index(self, inter_mat):
        rows = inter_mat.row
        cols = inter_mat.col + self.n_users
        return np.column_stack((rows, cols))

    def item_item(self, rep):
        h = rep
        for i in range(self.n_layers):
            h = torch.sparse.mm(self.mm_adj, h)
        return rep + h

    def get_forward_edge_mask(self):
        """Return the learned weight for every forward user-item edge."""
        return torch.sigmoid(self.mask_logits)

    def get_user_edge_ids(self, user_id):
        """Return mask-logit indices for train edges incident to ``user_id``."""
        user_id = int(user_id)
        if user_id < 0 or user_id >= self.num_user:
            raise ValueError(
                'user_id must be in [0, {}), got {}.'.format(
                    self.num_user,
                    user_id
                )
            )
        return torch.nonzero(
            self.forward_edge_users == user_id,
            as_tuple=False
        ).flatten()

    def get_counterfactual_forward_mask(self, edge_id, base_mask=None):
        """Clone a forward mask and set exactly one learned edge weight to 0."""
        edge_id = int(edge_id)
        if edge_id < 0 or edge_id >= self.num_interactions:
            raise ValueError(
                'edge_id must be in [0, {}), got {}.'.format(
                    self.num_interactions,
                    edge_id
                )
            )

        if base_mask is None:
            base_mask = self.get_forward_edge_mask()
        self._validate_forward_edge_mask(base_mask)

        counterfactual_mask = base_mask.clone()
        counterfactual_mask[edge_id] = 0.0
        return counterfactual_mask

    def _validate_forward_edge_mask(self, forward_edge_mask):
        if not torch.is_tensor(forward_edge_mask):
            raise TypeError('forward_edge_mask must be a torch.Tensor.')
        if forward_edge_mask.dim() != 1:
            raise ValueError(
                'forward_edge_mask must be one-dimensional, got shape {}.'
                .format(tuple(forward_edge_mask.shape))
            )
        if forward_edge_mask.numel() != self.num_interactions:
            raise ValueError(
                'forward_edge_mask has {} values, expected {}.'
                .format(
                    forward_edge_mask.numel(),
                    self.num_interactions
                )
            )

    def compute_full_view(self):
        """
        Compute the invariant full-GCN view used by counterfactual inference.

        The returned tuple contains raw full-branch user and item
        representations.  It can safely be reused while only the masked branch
        is intervened on; the joint item-item operator is still applied after
        concatenating both branches to preserve the original computation.
        """
        self.full_rep, self.full_preference = self.full_gcn(
            self.edge_index,
            self.id_embedding_full.weight
        )
        full_user_rep = self.full_rep[:self.num_user]
        full_item_rep = self.full_rep[self.num_user:]
        return full_user_rep, full_item_rep

    def compute_result_embedding(self, forward_edge_mask=None, full_view=None):
        """
        Build recommendation embeddings with an optional masked-branch override.

        ``forward_edge_mask`` has one value per original user-item interaction.
        Each value is duplicated internally for the reverse item-user edge.
        Supplying ``full_view`` avoids recomputing the invariant full branch.
        """
        if forward_edge_mask is None:
            forward_edge_mask = self.get_forward_edge_mask()
        self._validate_forward_edge_mask(forward_edge_mask)

        forward_edge_mask = forward_edge_mask.to(
            device=self.edge_index.device,
            dtype=self.id_embedding_masked.weight.dtype
        )
        edge_mask = torch.cat(
            [forward_edge_mask, forward_edge_mask],
            dim=0
        )

        if full_view is None:
            full_user_rep, full_item_rep = self.compute_full_view()
        else:
            if not isinstance(full_view, (tuple, list)) or len(full_view) != 2:
                raise TypeError(
                    'full_view must be a (user_rep, item_rep) pair.'
                )
            full_user_rep, full_item_rep = full_view
            if full_user_rep.shape[0] != self.num_user:
                raise ValueError('full_view contains an invalid user count.')
            if full_item_rep.shape[0] != self.num_item:
                raise ValueError('full_view contains an invalid item count.')

        self.mask_rep, self.mask_preference = self.mask_gcn(
            self.edge_index,
            self.id_embedding_masked.weight,
            edge_mask=edge_mask
        )

        masked_user_rep = self.mask_rep[:self.num_user]
        masked_item_rep = self.mask_rep[self.num_user:]

        user_rep = torch.cat(
            [full_user_rep, masked_user_rep],
            dim=1
        )
        item_rep = torch.cat(
            [full_item_rep, masked_item_rep],
            dim=1
        )
        item_rep = self.item_item(item_rep)

        # Keep the two post-GCN views separately for MIPD.  item_item is a
        # linear propagation applied column-wise, so splitting its output is
        # exactly equivalent to applying it to each branch independently.
        view_dim = full_user_rep.size(1)
        self.full_user_view = full_user_rep
        self.masked_user_view = masked_user_rep
        self.full_item_view = item_rep[:, :view_dim]
        self.masked_item_view = item_rep[:, view_dim:]

        self.result_embed = torch.cat([user_rep, item_rep], dim=0)
        return self.result_embed

    @staticmethod
    def _js_divergence_from_logits(p_logits, q_logits):
        """Jensen-Shannon divergence between two batches of logits."""
        p = F.softmax(p_logits, dim=1)
        q = F.softmax(q_logits, dim=1)
        mixture = 0.5 * (p + q)

        # Clamp only inside log to avoid log(0), while retaining the original
        # probabilities as KL targets.
        eps = torch.finfo(mixture.dtype).eps
        log_mixture = mixture.clamp_min(eps).log()
        return 0.5 * (
            F.kl_div(log_mixture, p, reduction='batchmean')
            + F.kl_div(log_mixture, q, reduction='batchmean')
        )

    def _get_view_preference_features(self, interaction):
        """
        Return sample-level Full and Mask features for BPR triplets.

        For a triplet (u, i+, i-), each view is represented by
        u * (i+ - i-).  Summing its last dimension gives exactly that view's
        contribution to the positive-minus-negative ranking margin.
        """
        user_nodes, pos_item_nodes, neg_item_nodes = (
            interaction[0], interaction[1], interaction[2]
        )

        full_feature = self.full_user_view[user_nodes] * (
            self.full_item_view[pos_item_nodes]
            - self.full_item_view[neg_item_nodes]
        )
        masked_feature = self.masked_user_view[user_nodes] * (
            self.masked_item_view[pos_item_nodes]
            - self.masked_item_view[neg_item_nodes]
        )
        return full_feature, masked_feature

    def calculate_mipd_loss(self, interaction):
        """
        Estimate Mask's task-relevant complementary contribution with MIPD.

        The Full feature is the fixed conditioning view.  Only the sample-level
        Mask feature is permuted after both GCN branches have run.  Minimizing
        the returned negative JSD maximizes the prediction change caused by
        breaking the Full-Mask pairing.
        """
        full_feature, masked_feature = self._get_view_preference_features(
            interaction
        )
        batch_size = masked_feature.size(0)
        if batch_size < 2 or self.mipd_weight == 0.0:
            zero = masked_feature.sum() * 0.0
            return zero, zero.detach()

        # Asymmetric MIPD: Full is the conditioning/anchor branch for this
        # regularizer.  It is still trained normally by the ranking loss.
        full_feature = full_feature.detach()
        base_margin = (full_feature + masked_feature).sum(dim=1)
        base_logits = torch.stack(
            [torch.zeros_like(base_margin), base_margin],
            dim=1
        ) / self.mipd_temperature

        jsd_values = []
        for _ in range(self.mipd_num_samples):
            permutation = torch.randperm(
                batch_size,
                device=masked_feature.device
            )
            shuffled_masked_feature = masked_feature[permutation]
            perturbed_margin = (
                full_feature + shuffled_masked_feature
            ).sum(dim=1)
            perturbed_logits = torch.stack(
                [torch.zeros_like(perturbed_margin), perturbed_margin],
                dim=1
            ) / self.mipd_temperature
            jsd_values.append(
                self._js_divergence_from_logits(
                    base_logits,
                    perturbed_logits
                )
            )

        mipd_jsd = torch.stack(jsd_values).mean()
        mipd_loss = -mipd_jsd
        return mipd_loss, mipd_jsd.detach()

    def forward(self, interaction):
        user_nodes, pos_item_nodes, neg_item_nodes = interaction[0], interaction[1], interaction[2]
        pos_item_nodes = pos_item_nodes + self.n_users
        neg_item_nodes = neg_item_nodes + self.n_users

        # item_feat = self.mlp_item(self.t_feat)
        # user_feat = F.normalize(self.mlp_user(self.user_feat))

        # self.idl_rep, self.t_preference = self.idl_gcn(self.edge_index, self.id_embedding_low.weight)
        # self.idh_rep, self.id_preference = self.idh_gcn(self.edge_index, self.id_embedding_high.weight)

        self.compute_result_embedding()
        user_tensor = self.result_embed[user_nodes]
        pos_item_tensor = self.result_embed[pos_item_nodes]
        neg_item_tensor = self.result_embed[neg_item_nodes]
        pos_scores = torch.sum(user_tensor * pos_item_tensor, dim=1)
        neg_scores = torch.sum(user_tensor * neg_item_tensor, dim=1)
        return pos_scores, neg_scores

    def calculate_loss(self, interaction):
        pos_scores, neg_scores = self.forward(interaction)
        # Stable equivalent of -log2(sigmoid(pos_scores - neg_scores)).
        ranking_loss = F.softplus(-(pos_scores - neg_scores)).mean()
        ranking_loss = ranking_loss / np.log(2.0)

        mipd_loss, mipd_jsd = self.calculate_mipd_loss(interaction)
        total_loss = ranking_loss + self.mipd_weight * mipd_loss

        self.last_ranking_loss = ranking_loss.detach()
        self.last_mipd_loss = mipd_loss.detach()
        self.last_mipd_jsd = mipd_jsd
        return total_loss

    def full_sort_predict(self, interaction):
        if not hasattr(self, 'result_embed') or self.result_embed is None:
            self.compute_result_embedding()
        user_tensor = self.result_embed[:self.n_users]
        item_tensor = self.result_embed[self.n_users:]

        temp_user_tensor = user_tensor[interaction[0], :]
        score_matrix = torch.matmul(temp_user_tensor, item_tensor.t())
        return score_matrix

class GCN(torch.nn.Module):
    def __init__(self,datasets, batch_size, num_user, num_item, dim_id, aggr_mode, num_layer, has_feature, dropout,
                 dim_latent=None,device = None,features=None, user_profile=None):
        super(GCN, self).__init__()
        self.batch_size = batch_size
        self.num_user = num_user
        self.num_item = num_item
        self.datasets = datasets
        self.dim_id = dim_id
        self.dim_feat = features.size(1)
        self.dim_latent = dim_latent
        self.aggr_mode = aggr_mode
        self.has_feature = has_feature
        self.dropout = dropout
        self.device = device
        self.userprofile = user_profile

        if self.has_feature:
            self.preference = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
                np.random.randn(num_user, self.dim_latent), dtype=torch.float32, requires_grad=True),
                gain=1))
            self.conv_embed_1 = Base_gcn(self.dim_latent, self.dim_latent, aggr=self.aggr_mode)
        else:
            self.preference = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
                np.random.randn(num_user, self.dim_feat), dtype=torch.float32, requires_grad=True),
                gain=1))
            self.conv_embed_1 = Base_gcn(self.dim_latent, self.dim_latent, aggr=self.aggr_mode)

    def forward(self,edge_index,features, edge_mask = None):
        temp_features = features
        temp_profile = self.preference
        x = torch.cat((temp_profile, temp_features), dim=0)
        x = F.normalize(x)
        h = self.conv_embed_1(x, edge_index,edge_mask)  # equation 1
        h_1 = self.conv_embed_1(h, edge_index,edge_mask)  # equation 1
        h_2 = self.conv_embed_1(h_1, edge_index,edge_mask)

        x_hat =h + x + h_1 + h_2
        return x_hat, self.preference


class Base_gcn(MessagePassing):
    def __init__(self, in_channels, out_channels, normalize=True, bias=True, aggr='add', **kwargs):
        super(Base_gcn, self).__init__(aggr=aggr, **kwargs)
        self.aggr = aggr
        self.in_channels = in_channels
        self.out_channels = out_channels

    def forward(self, x, edge_index,edge_mask=None, size=None):
        # pdb.set_trace()

        if edge_mask is None:
            edge_mask = torch.ones(
                edge_index.size(1),
                device=x.device,
                dtype=x.dtype
            )

        if size is None:
            edge_index, _ = remove_self_loops(edge_index)
            # edge_index, _ = add_self_loops(edge_index, num_nodes=x.size(0))
        x = x.unsqueeze(-1) if x.dim() == 1 else x
        # pdb.set_trace()
        return self.propagate(edge_index, size=(x.size(0), x.size(0)), x=x, edge_mask = edge_mask)

    def message(self, x_j, edge_index, size,edge_mask):
        if self.aggr == 'add':
            # pdb.set_trace()
            row, col = edge_index
            deg = degree(row, size[0], dtype=x_j.dtype)
            deg_inv_sqrt = deg.pow(-0.5)
            deg_inv_sqrt[
            torch.isinf(deg_inv_sqrt)
            ] = 0

            norm = deg_inv_sqrt[row] * deg_inv_sqrt[col]
            # return norm.view(-1, 1) * x_j
            return (
                norm.view(-1, 1)
                * edge_mask.view(-1, 1)
                * x_j
            )
        return x_j

    def update(self, aggr_out):
        return aggr_out

    def __repr(self):
        return '{}({},{})'.format(self.__class__.__name__, self.in_channels, self.out_channels)