# coding: utf-8
# 
#
# user-graph need to be generated by the following script
# tools/generate-u-u-matrix.py
import os
import math
import numpy as np
import scipy.sparse as sp
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn.conv import MessagePassing
from torch_geometric.utils import remove_self_loops, add_self_loops, degree
import torch_geometric

from common.abstract_recommender import GeneralRecommender
from common.loss import BPRLoss, EmbLoss
from common.init import xavier_uniform_initialization
from torch.nn import MultiheadAttention
# from .transformer import TransformerEncoder


def _cfg(config, key, default):
    """Read an optional config value without assuming config implements .get()."""
    try:
        value = config[key]
    except Exception:
        return default
    return default if value is None else value

class MASKED_PERSONALIZED(GeneralRecommender):
    def __init__(self, config, dataset):
        super(MASKED_PERSONALIZED, self).__init__(config, dataset)

        num_user = self.n_users
        num_item = self.n_items
        print('number of users: {}, number of items: {}'.format(num_user, num_item))
        
        batch_size = config['train_batch_size']         # not used
        dim_x = config['embedding_size']
        self.feat_embed_dim = config['feat_embed_dim']
        self.n_layers = config['n_mm_layers']
        self.knn_k = config['knn_k']

        self.batch_size = batch_size
        self.num_user = num_user
        self.num_item = num_item
        self.k = 40
        self.aggr_mode = config['aggr_mode']
        self.user_aggr_mode = 'softmax'
        self.num_layer = 1
        self.dataset = dataset
        self.reg_weight = config['reg_weight']
        self.drop_rate = 0.1
        self.t_rep = None
        self.t_preference = None
        self.dim_latent = 64
        self.mm_adj = None
        self.config = config

        # Personalized sufficient / necessary interaction-set objective.
        # Setting both weights to 0 recovers the original Full + Mask loss.
        self.cf_suff_weight = float(_cfg(config, 'cf_suff_weight', 0.01))
        self.cf_nec_weight = float(_cfg(config, 'cf_nec_weight', 0.01))
        self.cf_top_ratio = float(_cfg(config, 'cf_top_ratio', 0.50))
        self.cf_suff_tolerance = float(_cfg(config, 'cf_suff_tolerance', 0.20))
        self.cf_nec_margin = float(_cfg(config, 'cf_nec_margin', 0.20))
        self.cf_min_user_degree = int(_cfg(config, 'cf_min_user_degree', 2))
        self.cf_confidence_threshold = float(_cfg(config, 'cf_confidence_threshold', 0.0))
        self.cf_confidence_temperature = float(_cfg(config, 'cf_confidence_temperature', 1.0))
        self.cf_eps = 1e-8

        if self.cf_suff_weight < 0.0:
            raise ValueError('cf_suff_weight must be >= 0.')
        if self.cf_nec_weight < 0.0:
            raise ValueError('cf_nec_weight must be >= 0.')
        if not (0.0 < self.cf_top_ratio <= 1.0):
            raise ValueError('Require 0 < cf_top_ratio <= 1.')
        if self.cf_suff_tolerance < 0.0:
            raise ValueError('cf_suff_tolerance must be >= 0.')
        if self.cf_nec_margin < 0.0:
            raise ValueError('cf_nec_margin must be >= 0.')
        if self.cf_min_user_degree < 1:
            raise ValueError('cf_min_user_degree must be >= 1.')
        if self.cf_confidence_temperature <= 0.0:
            raise ValueError('cf_confidence_temperature must be > 0.')

        dataset_path = os.path.abspath(config['data_path'] + config['dataset'])
        
        mm_adj_file = os.path.join(dataset_path, 'mm_adj_{}.pt'.format(self.knn_k))

        # self.id_embedding_low = nn.Embedding(num_item, self.feat_embed_dim)
        # self.id_embedding_high = nn.Embedding(num_item, self.feat_embed_dim)
        self.id_embedding_full = nn.Embedding(num_item, self.feat_embed_dim)
        self.id_embedding_masked = nn.Embedding(num_item, self.feat_embed_dim)

        self.mlp_item = nn.Linear(self.t_feat.shape[-1], self.dim_latent, bias=False)
        self.mlp_user = nn.Linear(self.user_feat.shape[-1], self.dim_latent, bias=False)

        indices, text_adj = self.get_knn_adj_mat(self.t_feat)
        self.mm_adj = text_adj

        train_interactions = dataset.inter_matrix(form='coo').astype(np.float32)

        edge_index = self.pack_edge_index(train_interactions)

        self.num_interactions = edge_index.shape[0]

        # Group the E unique forward user->item edges by user.
        forward_user_ids_np = edge_index[:, 0].astype(np.int64)
        user_degree_np = np.bincount(
            forward_user_ids_np,
            minlength=self.num_user
        ).astype(np.int64)

        edge_order_np = np.argsort(
            forward_user_ids_np,
            kind='stable'
        ).astype(np.int64)

        user_ptr_np = np.zeros(self.num_user + 1, dtype=np.int64)
        user_ptr_np[1:] = np.cumsum(user_degree_np)

        self.register_buffer(
            'cf_user_degree',
            torch.tensor(user_degree_np, dtype=torch.long, device=self.device)
        )
        self.register_buffer(
            'cf_edge_order',
            torch.tensor(edge_order_np, dtype=torch.long, device=self.device)
        )
        self.register_buffer(
            'cf_user_ptr',
            torch.tensor(user_ptr_np, dtype=torch.long, device=self.device)
        )

        self.loss_components = {}

        edge_index = torch.tensor(edge_index, 
                                  dtype=torch.long,
                                  device = self.device).t().contiguous()

        self.edge_index = torch.cat(
                            [edge_index, edge_index[[1, 0]]],
                            dim=1
                        )

        self.mask_logits = nn.Parameter(
                            torch.zeros(
                                self.num_interactions,
                                device=self.device
                            )
                        )

        edge_index = self.pack_edge_index(train_interactions)

        item_ids = edge_index[:, 1] - self.num_user
        item_degree = np.bincount(item_ids, minlength=self.num_item)

        high_ratio = 0.10
        num_high = int(self.num_item * high_ratio)

        high_items = np.argsort(item_degree)[-num_high:]
        high_items = set(high_items.tolist())

        low_edges = []
        high_edges = []

        for edge in edge_index:
            item_id = edge[1] - self.num_user

            if item_id in high_items:
                high_edges.append(edge)
            else:
                low_edges.append(edge)

        low_edges = np.array(low_edges, dtype=np.int64)
        high_edges = np.array(high_edges, dtype=np.int64)

        self.edge_index_low = torch.tensor(low_edges, dtype=torch.long).t().contiguous().to(self.device)
        self.edge_index_high = torch.tensor(high_edges, dtype=torch.long).t().contiguous().to(self.device)

        self.edge_index_low = torch.cat(
            (self.edge_index_low, self.edge_index_low[[1, 0]]),
            dim=1
        )

        self.edge_index_high = torch.cat(
            (self.edge_index_high, self.edge_index_high[[1, 0]]),
            dim=1
        )
        # self.edge = concat 2 edge_index to make the graph undirected
        # self.edge_index = torch.cat((self.edge_index_low, self.edge_index_high), dim=1)

        # self.idl_gcn = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
        #                 num_layer=self.num_layer, has_feature=False, dropout=self.drop_rate, dim_latent=64,
        #                 device=self.device, features=self.id_embedding.weight)
        # self.idh_gcn = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
        #                 num_layer=self.num_layer, has_feature=False, dropout=self.drop_rate, dim_latent=64,
        #                 device=self.device, features=self.id_embedding.weight)

        self.full_gcn = GCN(
                        self.dataset,
                        batch_size,
                        num_user,
                        num_item,
                        dim_x,
                        self.aggr_mode,
                        num_layer=self.num_layer,
                        has_feature=False,
                        dropout=self.drop_rate,
                        dim_latent=64,
                        device=self.device,
                        features=self.id_embedding_full.weight
                    )

        self.mask_gcn = GCN(
            self.dataset,
            batch_size,
            num_user,
            num_item,
            dim_x,
            self.aggr_mode,
            num_layer=self.num_layer,
            has_feature=False,
            dropout=self.drop_rate,
            dim_latent=64,
            device=self.device,
            features=self.id_embedding_masked.weight
        )
        fusion = config['fusion'] or 'add'
        if fusion in ['add', 'pool']:
            pass
        elif fusion == 'Multi-Head Attention':
            self.multihead_attn = nn.MultiheadAttention(embed_dim=64, num_heads=4)
        elif fusion == 'Transformer':
            self.transformer = TransformerEncoder(64, num_heads= 4, layers=2)
        else:
            raise NotImplementedError
        


    def get_knn_adj_mat(self, mm_embeddings):
        context_norm = mm_embeddings.div(torch.norm(mm_embeddings, p=2, dim=-1, keepdim=True))
        sim = torch.mm(context_norm, context_norm.transpose(1, 0))
        _, knn_ind = torch.topk(sim, self.knn_k, dim=-1)
        adj_size = sim.size()
        del sim
        # construct sparse adj
        indices0 = torch.arange(knn_ind.shape[0]).to(self.device)
        indices0 = torch.unsqueeze(indices0, 1)
        indices0 = indices0.expand(-1, self.knn_k)
        indices = torch.stack((torch.flatten(indices0), torch.flatten(knn_ind)), 0)
        # norm
        return indices, self.compute_normalized_laplacian(indices, adj_size)
    
    def compute_normalized_laplacian(self, indices, adj_size):
        adj = torch.sparse.FloatTensor(indices, torch.ones_like(indices[0]), adj_size)
        row_sum = 1e-7 + torch.sparse.sum(adj, -1).to_dense()
        r_inv_sqrt = torch.pow(row_sum, -0.5)
        rows_inv_sqrt = r_inv_sqrt[indices[0]]
        cols_inv_sqrt = r_inv_sqrt[indices[1]]
        values = rows_inv_sqrt * cols_inv_sqrt
        return torch.sparse.FloatTensor(indices, values, adj_size)

    def pack_edge_index(self, inter_mat):
        rows = inter_mat.row
        cols = inter_mat.col + self.n_users
        return np.column_stack((rows, cols))

    def item_item(self, rep):
        h = rep
        for i in range(self.n_layers):
            h = torch.sparse.mm(self.mm_adj, h)
        return rep + h

    def fuse_full_and_mask(self, full_rep, mask_rep):
        item_full = full_rep[self.num_user:]
        item_mask = mask_rep[self.num_user:]
        item_rep = torch.cat((item_full, item_mask), dim=1)
        item_rep = self.item_item(item_rep)

        user_full = full_rep[:self.num_user]
        user_mask = mask_rep[:self.num_user]
        user_rep = torch.cat((user_full, user_mask), dim=1)

        return torch.cat((user_rep, item_rep), dim=0)

    def pairwise_scores(self, representation, interaction):
        user_nodes = interaction[0]
        pos_item_nodes = interaction[1] + self.n_users
        neg_item_nodes = interaction[2] + self.n_users

        user_tensor = representation[user_nodes]
        pos_item_tensor = representation[pos_item_nodes]
        neg_item_tensor = representation[neg_item_nodes]

        pos_scores = torch.sum(user_tensor * pos_item_tensor, dim=1)
        neg_scores = torch.sum(user_tensor * neg_item_tensor, dim=1)
        return pos_scores, neg_scores

    def build_personalized_intervention_masks(self, base_mask, batch_users):
        """Build KEEP/REMOVE masks for top-mask edges of active users."""
        unique_users = torch.unique(batch_users)
        degrees = self.cf_user_degree[unique_users]
        eligible_users = unique_users[degrees >= self.cf_min_user_degree]

        selected_top = torch.zeros(
            self.num_interactions,
            dtype=torch.bool,
            device=base_mask.device
        )
        active_user_edges = torch.zeros(
            self.num_interactions,
            dtype=torch.bool,
            device=base_mask.device
        )

        with torch.no_grad():
            detached_mask = base_mask.detach()

            for user_id_tensor in eligible_users:
                u = int(user_id_tensor.item())
                start = int(self.cf_user_ptr[u].item())
                end = int(self.cf_user_ptr[u + 1].item())
                if end <= start:
                    continue

                edge_ids = self.cf_edge_order[start:end]
                active_user_edges[edge_ids] = True
                degree_u = end - start
                k = max(1, int(math.ceil(self.cf_top_ratio * degree_u)))
                k = min(k, degree_u)

                if k == degree_u:
                    chosen = edge_ids
                else:
                    local_scores = detached_mask[edge_ids]
                    chosen_local = torch.topk(
                        local_scores,
                        k=k,
                        largest=True,
                        sorted=False
                    ).indices
                    chosen = edge_ids[chosen_local]

                selected_top[chosen] = True

        # KEEP: for active users, suppress their non-selected edges.
        # Non-active users remain unchanged.
        keep_gate = ((~active_user_edges) | selected_top).to(base_mask.dtype)
        keep_mask = base_mask * keep_gate

        # REMOVE: delete only the selected top-mask edges.
        remove_gate = (~selected_top).to(base_mask.dtype)
        remove_mask = base_mask * remove_gate

        return keep_mask, remove_mask, selected_top, active_user_edges, eligible_users

    def forward(self, interaction, return_aux=False):
        self.full_rep, self.full_preference = self.full_gcn(
            self.edge_index,
            self.id_embedding_full.weight
        )

        mask = torch.sigmoid(self.mask_logits)
        edge_mask = torch.cat([mask, mask], dim=0)

        self.mask_rep, self.mask_preference = self.mask_gcn(
            self.edge_index,
            self.id_embedding_masked.weight,
            edge_mask=edge_mask
        )

        self.result_embed = self.fuse_full_and_mask(
            self.full_rep,
            self.mask_rep
        )

        pos_scores, neg_scores = self.pairwise_scores(
            self.result_embed,
            interaction
        )

        if not return_aux:
            return pos_scores, neg_scores

        return pos_scores, neg_scores, {
            'mask': mask,
            'full_rep': self.full_rep,
            'mask_rep': self.mask_rep,
        }

    def calculate_loss(self, interaction):
        # Exact original Full + Mask control path.
        if self.cf_suff_weight == 0.0 and self.cf_nec_weight == 0.0:
            pos_scores, neg_scores = self.forward(interaction, return_aux=False)
            return -torch.mean(
                torch.log2(torch.sigmoid(pos_scores - neg_scores))
            )

        # Base/observed world.
        pos_scores, neg_scores, aux = self.forward(
            interaction,
            return_aux=True
        )
        base_margin = pos_scores - neg_scores
        bpr_loss = -torch.mean(torch.log2(torch.sigmoid(base_margin)))

        base_mask = aux['mask']
        keep_mask, remove_mask, selected_top, active_user_edges, eligible_users = (
            self.build_personalized_intervention_masks(
                base_mask=base_mask,
                batch_users=interaction[0]
            )
        )

        if eligible_users.numel() == 0:
            return bpr_loss

        # KEEP world: among each active user's own edges, retain only top-mask set.
        keep_edge_mask = torch.cat([keep_mask, keep_mask], dim=0)
        keep_mask_rep, _ = self.mask_gcn(
            self.edge_index,
            self.id_embedding_masked.weight,
            edge_mask=keep_edge_mask
        )
        keep_result_embed = self.fuse_full_and_mask(
            aux['full_rep'],
            keep_mask_rep
        )
        keep_pos_scores, keep_neg_scores = self.pairwise_scores(
            keep_result_embed,
            interaction
        )
        keep_margin = keep_pos_scores - keep_neg_scores

        # REMOVE world: delete the same top-mask set.
        remove_edge_mask = torch.cat([remove_mask, remove_mask], dim=0)
        remove_mask_rep, _ = self.mask_gcn(
            self.edge_index,
            self.id_embedding_masked.weight,
            edge_mask=remove_edge_mask
        )
        remove_result_embed = self.fuse_full_and_mask(
            aux['full_rep'],
            remove_mask_rep
        )
        remove_pos_scores, remove_neg_scores = self.pairwise_scores(
            remove_result_embed,
            interaction
        )
        remove_margin = remove_pos_scores - remove_neg_scores

        # Eligible/confident examples receive CF supervision.
        batch_user_degree = self.cf_user_degree[interaction[0]]
        eligible_sample = (
            batch_user_degree >= self.cf_min_user_degree
        ).to(base_margin.dtype)

        base_reference = base_margin.detach()
        confidence_weight = torch.sigmoid(
            (base_reference - self.cf_confidence_threshold)
            / self.cf_confidence_temperature
        )
        sample_weight = (eligible_sample * confidence_weight).detach()
        weight_sum = sample_weight.sum() + self.cf_eps

        # Sufficiency: KEEP should preserve the observed prediction.
        # keep_margin >= base_margin - tolerance
        suff_per_sample = F.softplus(
            base_reference
            - self.cf_suff_tolerance
            - keep_margin
        ) / math.log(2.0)
        suff_loss = (sample_weight * suff_per_sample).sum() / weight_sum

        # Necessity: REMOVE should reduce the observed prediction.
        # remove_margin <= base_margin - cf_nec_margin
        nec_per_sample = F.softplus(
            remove_margin
            - base_reference
            + self.cf_nec_margin
        ) / math.log(2.0)
        nec_loss = (sample_weight * nec_per_sample).sum() / weight_sum

        total_loss = (
            bpr_loss
            + self.cf_suff_weight * suff_loss
            + self.cf_nec_weight * nec_loss
        )

        with torch.no_grad():
            active_count = active_user_edges.float().sum()
            selected_count = selected_top.float().sum()
            selected_ratio = selected_count / (active_count + self.cf_eps)

            selected_mask_mean = (
                base_mask[selected_top].mean()
                if selected_top.any()
                else torch.tensor(0.0, device=base_mask.device)
            )
            active_nonselected = active_user_edges & (~selected_top)
            nonselected_mask_mean = (
                base_mask[active_nonselected].mean()
                if active_nonselected.any()
                else torch.tensor(0.0, device=base_mask.device)
            )

            suff_drop = base_reference - keep_margin
            nec_drop = base_reference - remove_margin
            valid = sample_weight > 0

            if valid.any():
                suff_satisfied = (
                    keep_margin[valid]
                    >= base_reference[valid] - self.cf_suff_tolerance
                ).float().mean()
                nec_satisfied = (
                    remove_margin[valid]
                    <= base_reference[valid] - self.cf_nec_margin
                ).float().mean()
            else:
                suff_satisfied = torch.tensor(0.0, device=base_mask.device)
                nec_satisfied = torch.tensor(0.0, device=base_mask.device)

            self.loss_components = {
                'total': float(total_loss.detach().cpu()),
                'bpr': float(bpr_loss.detach().cpu()),
                'suff_loss': float(suff_loss.detach().cpu()),
                'nec_loss': float(nec_loss.detach().cpu()),
                'weighted_suff_loss': float((self.cf_suff_weight * suff_loss).detach().cpu()),
                'weighted_nec_loss': float((self.cf_nec_weight * nec_loss).detach().cpu()),
                'base_margin_mean': float(base_margin.mean().detach().cpu()),
                'keep_margin_mean': float(keep_margin.mean().detach().cpu()),
                'remove_margin_mean': float(remove_margin.mean().detach().cpu()),
                'suff_drop_mean': float(suff_drop.mean().detach().cpu()),
                'nec_drop_mean': float(nec_drop.mean().detach().cpu()),
                'suff_satisfied_fraction': float(suff_satisfied.detach().cpu()),
                'nec_satisfied_fraction': float(nec_satisfied.detach().cpu()),
                'eligible_user_count': int(eligible_users.numel()),
                'selected_edge_ratio_active_users': float(selected_ratio.detach().cpu()),
                'selected_mask_mean': float(selected_mask_mean.detach().cpu()),
                'nonselected_mask_mean': float(nonselected_mask_mean.detach().cpu()),
                'mask_mean': float(base_mask.mean().detach().cpu()),
            }

        return total_loss

    def full_sort_predict(self, interaction):
        user_tensor = self.result_embed[:self.n_users]
        item_tensor = self.result_embed[self.n_users:]

        temp_user_tensor = user_tensor[interaction[0], :]
        score_matrix = torch.matmul(temp_user_tensor, item_tensor.t())
        return score_matrix

class GCN(torch.nn.Module):
    def __init__(self,datasets, batch_size, num_user, num_item, dim_id, aggr_mode, num_layer, has_feature, dropout,
                 dim_latent=None,device = None,features=None, user_profile=None):
        super(GCN, self).__init__()
        self.batch_size = batch_size
        self.num_user = num_user
        self.num_item = num_item
        self.datasets = datasets
        self.dim_id = dim_id
        self.dim_feat = features.size(1)
        self.dim_latent = dim_latent
        self.aggr_mode = aggr_mode
        self.has_feature = has_feature
        self.dropout = dropout
        self.device = device
        self.userprofile = user_profile

        if self.has_feature:
            self.preference = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
                np.random.randn(num_user, self.dim_latent), dtype=torch.float32, requires_grad=True),
                gain=1))
            self.conv_embed_1 = Base_gcn(self.dim_latent, self.dim_latent, aggr=self.aggr_mode)
        else:
            self.preference = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
                np.random.randn(num_user, self.dim_feat), dtype=torch.float32, requires_grad=True),
                gain=1))
            self.conv_embed_1 = Base_gcn(self.dim_latent, self.dim_latent, aggr=self.aggr_mode)

    def forward(self,edge_index,features, edge_mask = None):
        temp_features = features
        temp_profile = self.preference
        x = torch.cat((temp_profile, temp_features), dim=0)
        x = F.normalize(x)
        h = self.conv_embed_1(x, edge_index,edge_mask)  # equation 1
        h_1 = self.conv_embed_1(h, edge_index,edge_mask)  # equation 1
        h_2 = self.conv_embed_1(h_1, edge_index,edge_mask)

        x_hat =h + x + h_1 + h_2
        return x_hat, self.preference


class Base_gcn(MessagePassing):
    def __init__(self, in_channels, out_channels, normalize=True, bias=True, aggr='add', **kwargs):
        super(Base_gcn, self).__init__(aggr=aggr, **kwargs)
        self.aggr = aggr
        self.in_channels = in_channels
        self.out_channels = out_channels

    def forward(self, x, edge_index,edge_mask=None, size=None):
        # pdb.set_trace()

        if edge_mask is None:
            edge_mask = torch.ones(
                edge_index.size(1),
                device=x.device,
                dtype=x.dtype
            )

        if size is None:
            edge_index, _ = remove_self_loops(edge_index)
            # edge_index, _ = add_self_loops(edge_index, num_nodes=x.size(0))
        x = x.unsqueeze(-1) if x.dim() == 1 else x
        # pdb.set_trace()
        return self.propagate(edge_index, size=(x.size(0), x.size(0)), x=x, edge_mask = edge_mask)

    def message(self, x_j, edge_index, size,edge_mask):
        if self.aggr == 'add':
            # pdb.set_trace()
            row, col = edge_index
            deg = degree(row, size[0], dtype=x_j.dtype)
            deg_inv_sqrt = deg.pow(-0.5)
            deg_inv_sqrt[
            torch.isinf(deg_inv_sqrt)
            ] = 0

            norm = deg_inv_sqrt[row] * deg_inv_sqrt[col]
            # return norm.view(-1, 1) * x_j
            return (
                norm.view(-1, 1)
                * edge_mask.view(-1, 1)
                * x_j
            )
        return x_j

    def update(self, aggr_out):
        return aggr_out

    def __repr(self):
        return '{}({},{})'.format(self.__class__.__name__, self.in_channels, self.out_channels)


