# # coding: utf-8
# # 
# #
# # user-graph need to be generated by the following script
# # tools/generate-u-u-matrix.py
# import os
# import numpy as np
# import scipy.sparse as sp
# import torch
# import torch.nn as nn
# import torch.nn.functional as F
# from torch_geometric.nn.conv import MessagePassing
# from torch_geometric.utils import remove_self_loops, add_self_loops, degree
# import torch_geometric

# from common.abstract_recommender import GeneralRecommender
# from common.loss import BPRLoss, EmbLoss
# from common.init import xavier_uniform_initialization
# from torch.nn import MultiheadAttention
# # from .transformer import TransformerEncoder

# class MASKED_GLORIA_EX(GeneralRecommender):
#     def __init__(self, config, dataset):
#         super(MASKED_GLORIA_EX, self).__init__(config, dataset)

#         num_user = self.n_users
#         num_item = self.n_items
#         print('number of users: {}, number of items: {}'.format(num_user, num_item))
        
#         batch_size = config['train_batch_size']         # not used
#         dim_x = config['embedding_size']
#         self.feat_embed_dim = config['feat_embed_dim']
#         self.n_layers = config['n_mm_layers']
#         self.knn_k = config['knn_k']

#         self.batch_size = batch_size
#         self.num_user = num_user
#         self.num_item = num_item
#         self.k = 40
#         self.aggr_mode = config['aggr_mode']
#         self.user_aggr_mode = 'softmax'
#         self.num_layer = 1
#         self.dataset = dataset
#         self.reg_weight = config['reg_weight']
#         self.drop_rate = 0.1
#         self.t_rep = None
#         self.t_preference = None
#         self.dim_latent = 64
#         self.mm_adj = None
#         self.config = config
#         dataset_path = os.path.abspath(config['data_path'] + config['dataset'])
        
#         mm_adj_file = os.path.join(dataset_path, 'mm_adj_{}.pt'.format(self.knn_k))

#         # self.id_embedding_low = nn.Embedding(num_item, self.feat_embed_dim)
#         # self.id_embedding_high = nn.Embedding(num_item, self.feat_embed_dim)
#         self.id_embedding_full = nn.Embedding(num_item, self.feat_embed_dim)
#         self.id_embedding_masked = nn.Embedding(num_item, self.feat_embed_dim)

#         self.mlp_item = nn.Linear(self.t_feat.shape[-1], self.dim_latent, bias=False)
#         self.mlp_user = nn.Linear(self.user_feat.shape[-1], self.dim_latent, bias=False)

#         indices, text_adj = self.get_knn_adj_mat(self.t_feat)
#         self.mm_adj = text_adj

#         train_interactions = dataset.inter_matrix(form='coo').astype(np.float32)

#         edge_index = self.pack_edge_index(train_interactions)

#         self.num_interactions = edge_index.shape[0]

#         edge_index = torch.tensor(edge_index, 
#                                   dtype=torch.long,
#                                   device = self.device).t().contiguous()

#         self.edge_index = torch.cat(
#                             [edge_index, edge_index[[1, 0]]],
#                             dim=1
#                         )

#         self.mask_logits = nn.Parameter(
#                             torch.zeros(
#                                 self.num_interactions,
#                                 device=self.device
#                             )
#                         )

#         edge_index = self.pack_edge_index(train_interactions)

#         item_ids = edge_index[:, 1] - self.num_user
#         item_degree = np.bincount(item_ids, minlength=self.num_item)

#         high_ratio = 0.10
#         num_high = int(self.num_item * high_ratio)

#         high_items = np.argsort(item_degree)[-num_high:]
#         high_items = set(high_items.tolist())

#         low_edges = []
#         high_edges = []

#         for edge in edge_index:
#             item_id = edge[1] - self.num_user

#             if item_id in high_items:
#                 high_edges.append(edge)
#             else:
#                 low_edges.append(edge)

#         low_edges = np.array(low_edges, dtype=np.int64)
#         high_edges = np.array(high_edges, dtype=np.int64)

#         self.edge_index_low = torch.tensor(low_edges, dtype=torch.long).t().contiguous().to(self.device)
#         self.edge_index_high = torch.tensor(high_edges, dtype=torch.long).t().contiguous().to(self.device)

#         self.edge_index_low = torch.cat(
#             (self.edge_index_low, self.edge_index_low[[1, 0]]),
#             dim=1
#         )

#         self.edge_index_high = torch.cat(
#             (self.edge_index_high, self.edge_index_high[[1, 0]]),
#             dim=1
#         )
#         # self.edge = concat 2 edge_index to make the graph undirected
#         # self.edge_index = torch.cat((self.edge_index_low, self.edge_index_high), dim=1)

#         # self.idl_gcn = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
#         #                 num_layer=self.num_layer, has_feature=False, dropout=self.drop_rate, dim_latent=64,
#         #                 device=self.device, features=self.id_embedding.weight)
#         # self.idh_gcn = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
#         #                 num_layer=self.num_layer, has_feature=False, dropout=self.drop_rate, dim_latent=64,
#         #                 device=self.device, features=self.id_embedding.weight)

#         self.full_gcn = GCN(
#                         self.dataset,
#                         batch_size,
#                         num_user,
#                         num_item,
#                         dim_x,
#                         self.aggr_mode,
#                         num_layer=self.num_layer,
#                         has_feature=False,
#                         dropout=self.drop_rate,
#                         dim_latent=64,
#                         device=self.device,
#                         features=self.id_embedding_full.weight
#                     )

#         self.mask_gcn = GCN(
#             self.dataset,
#             batch_size,
#             num_user,
#             num_item,
#             dim_x,
#             self.aggr_mode,
#             num_layer=self.num_layer,
#             has_feature=False,
#             dropout=self.drop_rate,
#             dim_latent=64,
#             device=self.device,
#             features=self.id_embedding_masked.weight
#         )
#         if config['fusion'] in ['add', 'pool']:
#             pass
#         elif config['fusion'] == 'Multi-Head Attention':
#             self.multihead_attn = nn.MultiheadAttention(embed_dim=64, num_heads=4)
#         elif config['fusion'] == 'Transformer':
#             self.transformer = TransformerEncoder(64, num_heads= 4, layers=2)
#         else:
#             raise NotImplementedError
        


#     def get_knn_adj_mat(self, mm_embeddings):
#         context_norm = mm_embeddings.div(torch.norm(mm_embeddings, p=2, dim=-1, keepdim=True))
#         sim = torch.mm(context_norm, context_norm.transpose(1, 0))
#         _, knn_ind = torch.topk(sim, self.knn_k, dim=-1)
#         adj_size = sim.size()
#         del sim
#         # construct sparse adj
#         indices0 = torch.arange(knn_ind.shape[0]).to(self.device)
#         indices0 = torch.unsqueeze(indices0, 1)
#         indices0 = indices0.expand(-1, self.knn_k)
#         indices = torch.stack((torch.flatten(indices0), torch.flatten(knn_ind)), 0)
#         # norm
#         return indices, self.compute_normalized_laplacian(indices, adj_size)
    
#     def compute_normalized_laplacian(self, indices, adj_size):
#         adj = torch.sparse.FloatTensor(indices, torch.ones_like(indices[0]), adj_size)
#         row_sum = 1e-7 + torch.sparse.sum(adj, -1).to_dense()
#         r_inv_sqrt = torch.pow(row_sum, -0.5)
#         rows_inv_sqrt = r_inv_sqrt[indices[0]]
#         cols_inv_sqrt = r_inv_sqrt[indices[1]]
#         values = rows_inv_sqrt * cols_inv_sqrt
#         return torch.sparse.FloatTensor(indices, values, adj_size)

#     def pack_edge_index(self, inter_mat):
#         rows = inter_mat.row
#         cols = inter_mat.col + self.n_users
#         return np.column_stack((rows, cols))

#     def item_item(self, rep):
#         h = rep
#         for i in range(self.n_layers):
#             h = torch.sparse.mm(self.mm_adj, h)
#         return rep + h

#     def forward(self, interaction):
#         user_nodes, pos_item_nodes, neg_item_nodes = interaction[0], interaction[1], interaction[2]
#         pos_item_nodes += self.n_users
#         neg_item_nodes += self.n_users

#         # item_feat = self.mlp_item(self.t_feat)
#         # user_feat = F.normalize(self.mlp_user(self.user_feat))
        
#         # self.idl_rep, self.t_preference = self.idl_gcn(self.edge_index, self.id_embedding_low.weight)
#         # self.idh_rep, self.id_preference = self.idh_gcn(self.edge_index, self.id_embedding_high.weight)

#         self.full_rep, self.full_preference = self.full_gcn(
#                                                 self.edge_index,
#                                                 self.id_embedding_full.weight
#                                             )

#         mask = torch.sigmoid(self.mask_logits)

#         edge_mask = torch.cat(
#                         [mask, mask],
#                         dim=0
#                     )

#         self.mask_rep, self.mask_preference = self.mask_gcn(
#                                                 self.edge_index,
#                                                 self.id_embedding_masked.weight,
#                                                 edge_mask=edge_mask
#                                             )

#         item_repl = self.full_rep[self.num_user:]
#         item_reph = self.mask_rep[self.num_user:]

#         item_rep = torch.cat((item_repl, item_reph), dim=1)
#         item_rep = self.item_item(item_rep)

#         user_repl = self.full_rep[:self.num_user]
#         user_reph = self.mask_rep[:self.num_user]

#         user_rep = torch.cat((user_repl, user_reph), dim=1)

#         self.result_embed = torch.cat((user_rep, item_rep), dim=0)
#         user_tensor = self.result_embed[user_nodes]
#         pos_item_tensor = self.result_embed[pos_item_nodes]
#         neg_item_tensor = self.result_embed[neg_item_nodes]
#         pos_scores = torch.sum(user_tensor * pos_item_tensor, dim=1)
#         neg_scores = torch.sum(user_tensor * neg_item_tensor, dim=1)
#         return pos_scores, neg_scores

#     def calculate_loss(self, interaction):
#         pos_scores, neg_scores = self.forward(interaction)
#         bpr_loss = -torch.mean(torch.log2(torch.sigmoid(pos_scores - neg_scores)))

#         mask = torch.sigmoid(
#         self.mask_logits
#         )
#         self.lambda_cf = 0.1

#         cf_mask_loss = (
#             1.0 - mask
#         ).mean()

#         loss = (
#             bpr_loss
#             + self.lambda_cf * cf_mask_loss
#         )
#         return loss

#     def full_sort_predict(self, interaction):
#         user_tensor = self.result_embed[:self.n_users]
#         item_tensor = self.result_embed[self.n_users:]

#         temp_user_tensor = user_tensor[interaction[0], :]
#         score_matrix = torch.matmul(temp_user_tensor, item_tensor.t())
#         return score_matrix

# class GCN(torch.nn.Module):
#     def __init__(self,datasets, batch_size, num_user, num_item, dim_id, aggr_mode, num_layer, has_feature, dropout,
#                  dim_latent=None,device = None,features=None, user_profile=None):
#         super(GCN, self).__init__()
#         self.batch_size = batch_size
#         self.num_user = num_user
#         self.num_item = num_item
#         self.datasets = datasets
#         self.dim_id = dim_id
#         self.dim_feat = features.size(1)
#         self.dim_latent = dim_latent
#         self.aggr_mode = aggr_mode
#         self.has_feature = has_feature
#         self.dropout = dropout
#         self.device = device
#         self.userprofile = user_profile

#         if self.has_feature:
#             self.preference = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
#                 np.random.randn(num_user, self.dim_latent), dtype=torch.float32, requires_grad=True),
#                 gain=1))
#             self.conv_embed_1 = Base_gcn(self.dim_latent, self.dim_latent, aggr=self.aggr_mode)
#         else:
#             self.preference = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
#                 np.random.randn(num_user, self.dim_feat), dtype=torch.float32, requires_grad=True),
#                 gain=1))
#             self.conv_embed_1 = Base_gcn(self.dim_latent, self.dim_latent, aggr=self.aggr_mode)

#     def forward(self,edge_index,features, edge_mask = None):
#         temp_features = features
#         temp_profile = self.preference
#         x = torch.cat((temp_profile, temp_features), dim=0)
#         x = F.normalize(x)
#         h = self.conv_embed_1(x, edge_index,edge_mask)  # equation 1
#         h_1 = self.conv_embed_1(h, edge_index,edge_mask)  # equation 1
#         h_2 = self.conv_embed_1(h_1, edge_index,edge_mask)

#         x_hat =h + x + h_1 + h_2
#         return x_hat, self.preference


# class Base_gcn(MessagePassing):
#     def __init__(self, in_channels, out_channels, normalize=True, bias=True, aggr='add', **kwargs):
#         super(Base_gcn, self).__init__(aggr=aggr, **kwargs)
#         self.aggr = aggr
#         self.in_channels = in_channels
#         self.out_channels = out_channels

#     def forward(self, x, edge_index,edge_mask=None, size=None):
#         # pdb.set_trace()

#         if edge_mask is None:
#             edge_mask = torch.ones(
#                 edge_index.size(1),
#                 device=x.device,
#                 dtype=x.dtype
#             )

#         if size is None:
#             edge_index, _ = remove_self_loops(edge_index)
#             # edge_index, _ = add_self_loops(edge_index, num_nodes=x.size(0))
#         x = x.unsqueeze(-1) if x.dim() == 1 else x
#         # pdb.set_trace()
#         return self.propagate(edge_index, size=(x.size(0), x.size(0)), x=x, edge_mask = edge_mask)

#     def message(self, x_j, edge_index, size,edge_mask):
#         if self.aggr == 'add':
#             # pdb.set_trace()
#             row, col = edge_index
#             deg = degree(row, size[0], dtype=x_j.dtype)
#             deg_inv_sqrt = deg.pow(-0.5)
#             deg_inv_sqrt[
#             torch.isinf(deg_inv_sqrt)
#             ] = 0

#             norm = deg_inv_sqrt[row] * deg_inv_sqrt[col]
#             # return norm.view(-1, 1) * x_j
#             return (
#                 norm.view(-1, 1)
#                 * edge_mask.view(-1, 1)
#                 * x_j
#             )
#         return x_j

#     def update(self, aggr_out):
#         return aggr_out

#     def __repr(self):
#         return '{}({},{})'.format(self.__class__.__name__, self.in_channels, self.out_channels)

# coding: utf-8
# 
#
# user-graph need to be generated by the following script
# tools/generate-u-u-matrix.py

##############################

# import os
# import numpy as np
# import scipy.sparse as sp
# import torch
# import torch.nn as nn
# import torch.nn.functional as F
# from torch_geometric.nn.conv import MessagePassing
# from torch_geometric.utils import remove_self_loops, add_self_loops, degree
# import torch_geometric

# from common.abstract_recommender import GeneralRecommender
# from common.loss import BPRLoss, EmbLoss
# from common.init import xavier_uniform_initialization
# from torch.nn import MultiheadAttention
# # from .transformer import TransformerEncoder

# class MASKED_GLORIA_EX(GeneralRecommender):
#     def __init__(self, config, dataset):
#         super(MASKED_GLORIA_EX, self).__init__(config, dataset)

#         num_user = self.n_users
#         num_item = self.n_items
#         print('number of users: {}, number of items: {}'.format(num_user, num_item))
        
#         batch_size = config['train_batch_size']         # not used
#         dim_x = config['embedding_size']
#         self.feat_embed_dim = config['feat_embed_dim']
#         self.n_layers = config['n_mm_layers']
#         self.knn_k = config['knn_k']

#         self.batch_size = batch_size
#         self.num_user = num_user
#         self.num_item = num_item
#         self.k = 40
#         self.aggr_mode = config['aggr_mode']
#         self.user_aggr_mode = 'softmax'
#         self.num_layer = 1
#         self.dataset = dataset
#         self.reg_weight = config['reg_weight']
#         self.drop_rate = 0.1
#         self.t_rep = None
#         self.t_preference = None
#         self.dim_latent = 64
#         self.mm_adj = None
#         self.config = config
#         dataset_path = os.path.abspath(config['data_path'] + config['dataset'])
        
#         mm_adj_file = os.path.join(dataset_path, 'mm_adj_{}.pt'.format(self.knn_k))

#         # self.id_embedding_low = nn.Embedding(num_item, self.feat_embed_dim)
#         # self.id_embedding_high = nn.Embedding(num_item, self.feat_embed_dim)
#         self.id_embedding_full = nn.Embedding(num_item, self.feat_embed_dim)
#         self.id_embedding_masked = nn.Embedding(num_item, self.feat_embed_dim)

#         self.mlp_item = nn.Linear(self.t_feat.shape[-1], self.dim_latent, bias=False)
#         self.mlp_user = nn.Linear(self.user_feat.shape[-1], self.dim_latent, bias=False)

#         indices, text_adj = self.get_knn_adj_mat(self.t_feat)
#         self.mm_adj = text_adj

#         train_interactions = dataset.inter_matrix(form='coo').astype(np.float32)

#         # ============================================================
#         # Original user-item edges (one direction only)
#         # ============================================================
#         edge_index = self.pack_edge_index(train_interactions)
#         self.num_interactions = edge_index.shape[0]

#         # edge_user_ids[e] tells us which user owns original edge e.
#         # Shape: [num_interactions]
#         #
#         # User-level scalar mask:
#         #     M_(u,i) = sigmoid(user_mask_logits[u])
#         self.register_buffer(
#             'edge_user_ids',
#             torch.tensor(
#                 edge_index[:, 0],
#                 dtype=torch.long,
#                 device=self.device
#             )
#         )

#         edge_index = torch.tensor(
#             edge_index,
#             dtype=torch.long,
#             device=self.device
#         ).t().contiguous()

#         # Keep the same undirected interaction graph as the original code.
#         self.edge_index = torch.cat(
#             [edge_index, edge_index[[1, 0]]],
#             dim=1
#         )

#         # ============================================================
#         # USER-LEVEL LEARNABLE SCALAR MASK
#         # ============================================================
#         # Original:
#         #     one learnable logit per interaction edge -> O(|E|)
#         #
#         # Here:
#         #     one learnable logit per user -> O(|U|)
#         #
#         # All interaction edges of user u receive the same scalar:
#         #     m_u = sigmoid(user_mask_logits[u])
#         #
#         # Initialize at zero so sigmoid(0)=0.5, matching the original
#         # edge-level mask initialization for a clean ablation.
#         self.user_mask_logits = nn.Parameter(
#             torch.zeros(
#                 self.num_user,
#                 device=self.device
#             )
#         )

#         edge_index = self.pack_edge_index(train_interactions)

#         item_ids = edge_index[:, 1] - self.num_user
#         item_degree = np.bincount(item_ids, minlength=self.num_item)

#         high_ratio = 0.10
#         num_high = int(self.num_item * high_ratio)

#         high_items = np.argsort(item_degree)[-num_high:]
#         high_items = set(high_items.tolist())

#         low_edges = []
#         high_edges = []

#         for edge in edge_index:
#             item_id = edge[1] - self.num_user

#             if item_id in high_items:
#                 high_edges.append(edge)
#             else:
#                 low_edges.append(edge)

#         low_edges = np.array(low_edges, dtype=np.int64)
#         high_edges = np.array(high_edges, dtype=np.int64)

#         self.edge_index_low = torch.tensor(low_edges, dtype=torch.long).t().contiguous().to(self.device)
#         self.edge_index_high = torch.tensor(high_edges, dtype=torch.long).t().contiguous().to(self.device)

#         self.edge_index_low = torch.cat(
#             (self.edge_index_low, self.edge_index_low[[1, 0]]),
#             dim=1
#         )

#         self.edge_index_high = torch.cat(
#             (self.edge_index_high, self.edge_index_high[[1, 0]]),
#             dim=1
#         )
#         # self.edge = concat 2 edge_index to make the graph undirected
#         # self.edge_index = torch.cat((self.edge_index_low, self.edge_index_high), dim=1)

#         # self.idl_gcn = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
#         #                 num_layer=self.num_layer, has_feature=False, dropout=self.drop_rate, dim_latent=64,
#         #                 device=self.device, features=self.id_embedding.weight)
#         # self.idh_gcn = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
#         #                 num_layer=self.num_layer, has_feature=False, dropout=self.drop_rate, dim_latent=64,
#         #                 device=self.device, features=self.id_embedding.weight)

#         self.full_gcn = GCN(
#                         self.dataset,
#                         batch_size,
#                         num_user,
#                         num_item,
#                         dim_x,
#                         self.aggr_mode,
#                         num_layer=self.num_layer,
#                         has_feature=False,
#                         dropout=self.drop_rate,
#                         dim_latent=64,
#                         device=self.device,
#                         features=self.id_embedding_full.weight
#                     )

#         self.mask_gcn = GCN(
#             self.dataset,
#             batch_size,
#             num_user,
#             num_item,
#             dim_x,
#             self.aggr_mode,
#             num_layer=self.num_layer,
#             has_feature=False,
#             dropout=self.drop_rate,
#             dim_latent=64,
#             device=self.device,
#             features=self.id_embedding_masked.weight
#         )
#         if config['fusion'] in ['add', 'pool']:
#             pass
#         elif config['fusion'] == 'Multi-Head Attention':
#             self.multihead_attn = nn.MultiheadAttention(embed_dim=64, num_heads=4)
#         elif config['fusion'] == 'Transformer':
#             self.transformer = TransformerEncoder(64, num_heads= 4, layers=2)
#         else:
#             raise NotImplementedError
        


#     def get_knn_adj_mat(self, mm_embeddings):
#         context_norm = mm_embeddings.div(torch.norm(mm_embeddings, p=2, dim=-1, keepdim=True))
#         sim = torch.mm(context_norm, context_norm.transpose(1, 0))
#         _, knn_ind = torch.topk(sim, self.knn_k, dim=-1)
#         adj_size = sim.size()
#         del sim
#         # construct sparse adj
#         indices0 = torch.arange(knn_ind.shape[0]).to(self.device)
#         indices0 = torch.unsqueeze(indices0, 1)
#         indices0 = indices0.expand(-1, self.knn_k)
#         indices = torch.stack((torch.flatten(indices0), torch.flatten(knn_ind)), 0)
#         # norm
#         return indices, self.compute_normalized_laplacian(indices, adj_size)
    
#     def compute_normalized_laplacian(self, indices, adj_size):
#         adj = torch.sparse.FloatTensor(indices, torch.ones_like(indices[0]), adj_size)
#         row_sum = 1e-7 + torch.sparse.sum(adj, -1).to_dense()
#         r_inv_sqrt = torch.pow(row_sum, -0.5)
#         rows_inv_sqrt = r_inv_sqrt[indices[0]]
#         cols_inv_sqrt = r_inv_sqrt[indices[1]]
#         values = rows_inv_sqrt * cols_inv_sqrt
#         return torch.sparse.FloatTensor(indices, values, adj_size)

#     def pack_edge_index(self, inter_mat):
#         rows = inter_mat.row
#         cols = inter_mat.col + self.n_users
#         return np.column_stack((rows, cols))

#     def item_item(self, rep):
#         h = rep
#         for i in range(self.n_layers):
#             h = torch.sparse.mm(self.mm_adj, h)
#         return rep + h

#     def get_user_mask(self):
#         """Return one learned scalar mask value for each user."""
#         return torch.sigmoid(self.user_mask_logits)

#     def get_original_edge_mask(self):
#         """
#         Expand user-level scalar masks to the original user-item edges.

#         For original edge e=(u,i):
#             edge_mask[e] = sigmoid(user_mask_logits[u])
#         """
#         user_mask = self.get_user_mask()
#         return user_mask[self.edge_user_ids]

#     @torch.no_grad()
#     def get_user_mask_statistics(self):
#         """Diagnostics for the learned user-level mask."""
#         user_mask = self.get_user_mask().detach()
#         return {
#             'mean_keep': user_mask.mean().item(),
#             'mean_attenuation': (1.0 - user_mask).mean().item(),
#             'min_keep': user_mask.min().item(),
#             'max_keep': user_mask.max().item(),
#             'std_keep': user_mask.std(unbiased=False).item(),
#         }

#     def forward(self, interaction):
#         user_nodes = interaction[0]
#         pos_item_nodes = interaction[1] + self.n_users
#         neg_item_nodes = interaction[2] + self.n_users

#         # item_feat = self.mlp_item(self.t_feat)
#         # user_feat = F.normalize(self.mlp_user(self.user_feat))
        
#         # self.idl_rep, self.t_preference = self.idl_gcn(self.edge_index, self.id_embedding_low.weight)
#         # self.idh_rep, self.id_preference = self.idh_gcn(self.edge_index, self.id_embedding_high.weight)

#         self.full_rep, self.full_preference = self.full_gcn(
#                                                 self.edge_index,
#                                                 self.id_embedding_full.weight
#                                             )

#         # ============================================================
#         # User-level scalar mask
#         # ============================================================
#         # user_mask: [num_user]
#         # mask:      [num_interactions]
#         #
#         # Every interaction edge of the same user receives the same
#         # learned scalar weight.
#         user_mask = self.get_user_mask()
#         mask = user_mask[self.edge_user_ids]

#         # self.edge_index = original edges + reverse edges.
#         # Use the same user-conditioned mask in both directions.
#         edge_mask = torch.cat(
#             [mask, mask],
#             dim=0
#         )

#         self.mask_rep, self.mask_preference = self.mask_gcn(
#                                                 self.edge_index,
#                                                 self.id_embedding_masked.weight,
#                                                 edge_mask=edge_mask
#                                             )

#         item_repl = self.full_rep[self.num_user:]
#         item_reph = self.mask_rep[self.num_user:]

#         item_rep = torch.cat((item_repl, item_reph), dim=1)
#         item_rep = self.item_item(item_rep)

#         user_repl = self.full_rep[:self.num_user]
#         user_reph = self.mask_rep[:self.num_user]

#         user_rep = torch.cat((user_repl, user_reph), dim=1)

#         self.result_embed = torch.cat((user_rep, item_rep), dim=0)
#         user_tensor = self.result_embed[user_nodes]
#         pos_item_tensor = self.result_embed[pos_item_nodes]
#         neg_item_tensor = self.result_embed[neg_item_nodes]
#         pos_scores = torch.sum(user_tensor * pos_item_tensor, dim=1)
#         neg_scores = torch.sum(user_tensor * neg_item_tensor, dim=1)
#         return pos_scores, neg_scores

#     def calculate_loss(self, interaction):
#         pos_scores, neg_scores = self.forward(interaction)
#         loss_value = -torch.mean(torch.log2(torch.sigmoid(pos_scores - neg_scores)))
#         return loss_value

#     def full_sort_predict(self, interaction):
#         user_tensor = self.result_embed[:self.n_users]
#         item_tensor = self.result_embed[self.n_users:]

#         temp_user_tensor = user_tensor[interaction[0], :]
#         score_matrix = torch.matmul(temp_user_tensor, item_tensor.t())
#         return score_matrix

# class GCN(torch.nn.Module):
#     def __init__(self,datasets, batch_size, num_user, num_item, dim_id, aggr_mode, num_layer, has_feature, dropout,
#                  dim_latent=None,device = None,features=None, user_profile=None):
#         super(GCN, self).__init__()
#         self.batch_size = batch_size
#         self.num_user = num_user
#         self.num_item = num_item
#         self.datasets = datasets
#         self.dim_id = dim_id
#         self.dim_feat = features.size(1)
#         self.dim_latent = dim_latent
#         self.aggr_mode = aggr_mode
#         self.has_feature = has_feature
#         self.dropout = dropout
#         self.device = device
#         self.userprofile = user_profile

#         if self.has_feature:
#             self.preference = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
#                 np.random.randn(num_user, self.dim_latent), dtype=torch.float32, requires_grad=True),
#                 gain=1))
#             self.conv_embed_1 = Base_gcn(self.dim_latent, self.dim_latent, aggr=self.aggr_mode)
#         else:
#             self.preference = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
#                 np.random.randn(num_user, self.dim_feat), dtype=torch.float32, requires_grad=True),
#                 gain=1))
#             self.conv_embed_1 = Base_gcn(self.dim_latent, self.dim_latent, aggr=self.aggr_mode)

#     def forward(self,edge_index,features, edge_mask = None):
#         temp_features = features
#         temp_profile = self.preference
#         x = torch.cat((temp_profile, temp_features), dim=0)
#         x = F.normalize(x)
#         h = self.conv_embed_1(x, edge_index,edge_mask)  # equation 1
#         h_1 = self.conv_embed_1(h, edge_index,edge_mask)  # equation 1
#         h_2 = self.conv_embed_1(h_1, edge_index,edge_mask)

#         x_hat =h + x + h_1 + h_2
#         return x_hat, self.preference


# class Base_gcn(MessagePassing):
#     def __init__(self, in_channels, out_channels, normalize=True, bias=True, aggr='add', **kwargs):
#         super(Base_gcn, self).__init__(aggr=aggr, **kwargs)
#         self.aggr = aggr
#         self.in_channels = in_channels
#         self.out_channels = out_channels

#     def forward(self, x, edge_index,edge_mask=None, size=None):
#         # pdb.set_trace()

#         if edge_mask is None:
#             edge_mask = torch.ones(
#                 edge_index.size(1),
#                 device=x.device,
#                 dtype=x.dtype
#             )

#         if size is None:
#             edge_index, _ = remove_self_loops(edge_index)
#             # edge_index, _ = add_self_loops(edge_index, num_nodes=x.size(0))
#         x = x.unsqueeze(-1) if x.dim() == 1 else x
#         # pdb.set_trace()
#         return self.propagate(edge_index, size=(x.size(0), x.size(0)), x=x, edge_mask = edge_mask)

#     def message(self, x_j, edge_index, size,edge_mask):
#         if self.aggr == 'add':
#             # pdb.set_trace()
#             row, col = edge_index
#             deg = degree(row, size[0], dtype=x_j.dtype)
#             deg_inv_sqrt = deg.pow(-0.5)
#             deg_inv_sqrt[
#             torch.isinf(deg_inv_sqrt)
#             ] = 0

#             norm = deg_inv_sqrt[row] * deg_inv_sqrt[col]
#             # return norm.view(-1, 1) * x_j
#             return (
#                 norm.view(-1, 1)
#                 * edge_mask.view(-1, 1)
#                 * x_j
#             )
#         return x_j

#     def update(self, aggr_out):
#         return aggr_out

#     def __repr(self):
#         return '{}({},{})'.format(self.__class__.__name__, self.in_channels, self.out_channels)

######################################################

import os
import numpy as np
import scipy.sparse as sp
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn.conv import MessagePassing
from torch_geometric.utils import remove_self_loops, add_self_loops, degree
import torch_geometric

from common.abstract_recommender import GeneralRecommender
from common.loss import BPRLoss, EmbLoss
from common.init import xavier_uniform_initialization
from torch.nn import MultiheadAttention
# from .transformer import TransformerEncoder

class MASKED_GLORIA_EX(GeneralRecommender):
    def __init__(self, config, dataset):
        super(MASKED_GLORIA_EX, self).__init__(config, dataset)

        num_user = self.n_users
        num_item = self.n_items
        print('number of users: {}, number of items: {}'.format(num_user, num_item))
        
        batch_size = config['train_batch_size']         # not used
        dim_x = config['embedding_size']
        self.feat_embed_dim = config['feat_embed_dim']
        self.n_layers = config['n_mm_layers']
        self.knn_k = config['knn_k']

        self.batch_size = batch_size
        self.num_user = num_user
        self.num_item = num_item
        self.k = 40
        self.aggr_mode = config['aggr_mode']
        self.user_aggr_mode = 'softmax'
        self.num_layer = 1
        self.dataset = dataset
        self.reg_weight = config['reg_weight']
        self.drop_rate = 0.1
        self.t_rep = None
        self.t_preference = None
        self.dim_latent = 64
        self.mm_adj = None
        self.config = config
        dataset_path = os.path.abspath(config['data_path'] + config['dataset'])
        
        mm_adj_file = os.path.join(dataset_path, 'mm_adj_{}.pt'.format(self.knn_k))

        # self.id_embedding_low = nn.Embedding(num_item, self.feat_embed_dim)
        # self.id_embedding_high = nn.Embedding(num_item, self.feat_embed_dim)
        self.id_embedding_full = nn.Embedding(num_item, self.feat_embed_dim)
        self.id_embedding_masked = nn.Embedding(num_item, self.feat_embed_dim)

        self.mlp_item = nn.Linear(self.t_feat.shape[-1], self.dim_latent, bias=False)
        self.mlp_user = nn.Linear(self.user_feat.shape[-1], self.dim_latent, bias=False)

        indices, text_adj = self.get_knn_adj_mat(self.t_feat)
        self.mm_adj = text_adj

        train_interactions = dataset.inter_matrix(form='coo').astype(np.float32)

        # ============================================================
        # Original user-item edges (one direction only)
        # ============================================================
        edge_index = self.pack_edge_index(train_interactions)
        self.num_interactions = edge_index.shape[0]

        # edge_user_ids[e] tells us which user owns original edge e.
        # Shape: [num_interactions]
        #
        # User-level scalar mask:
        #     M_(u,i) = sigmoid(user_mask_logits[u])
        self.register_buffer(
            'edge_user_ids',
            torch.tensor(
                edge_index[:, 0],
                dtype=torch.long,
                device=self.device
            )
        )

        edge_index = torch.tensor(
            edge_index,
            dtype=torch.long,
            device=self.device
        ).t().contiguous()

        # Keep the same undirected interaction graph as the original code.
        self.edge_index = torch.cat(
            [edge_index, edge_index[[1, 0]]],
            dim=1
        )

        # ============================================================
        # USER-LEVEL LEARNABLE SCALAR MASK
        # ============================================================
        # Original:
        #     one learnable logit per interaction edge -> O(|E|)
        #
        # Here:
        #     one learnable logit per user -> O(|U|)
        #
        # All interaction edges of user u receive the same scalar:
        #     m_u = sigmoid(user_mask_logits[u])
        #
        # Initialize at zero so sigmoid(0)=0.5, matching the original
        # edge-level mask initialization for a clean ablation.
        self.user_mask_logits = nn.Parameter(
            torch.zeros(
                self.num_user,
                device=self.device
            )
        )

        # ============================================================
        # Counterfactual Neighborhood Response Learning
        # ============================================================
        # For a user with current mask m_u, construct two local
        # counterfactual interventions:
        #
        #     m_u^- = clip(m_u - delta, 0, 1)  -> MORE compression
        #     m_u^+ = clip(m_u + delta, 0, 1)  -> LESS compression
        #
        # We compare the factual BPR loss with the two counterfactual
        # losses, then move m_u toward the locally better intervention.
        #
        # IMPORTANT:
        #   - No adversarial training.
        #   - Counterfactual GCN passes are used as detached probes.
        #   - Only the user-mask scalar receives the response loss.
        #   - The original recommendation BPR still trains the full model.
        self.cf_delta = float(0.10)
        self.cf_response_weight = float(0.01)
        self.cf_min_improvement = float(0.0)
        self.cf_response_interval = int(1)

        # Internal counter used only to optionally reduce training cost.
        self._cf_train_step = 0

        # Diagnostics from the most recent response-learning step.
        self.cf_last_stats = {
            'response_loss': 0.0,
            'fraction_more_compression': 0.0,
            'fraction_less_compression': 0.0,
            'fraction_stable': 1.0,
            'mean_counterfactual_improvement': 0.0,
        }

        edge_index = self.pack_edge_index(train_interactions)

        item_ids = edge_index[:, 1] - self.num_user
        item_degree = np.bincount(item_ids, minlength=self.num_item)

        high_ratio = 0.10
        num_high = int(self.num_item * high_ratio)

        high_items = np.argsort(item_degree)[-num_high:]
        high_items = set(high_items.tolist())

        low_edges = []
        high_edges = []

        for edge in edge_index:
            item_id = edge[1] - self.num_user

            if item_id in high_items:
                high_edges.append(edge)
            else:
                low_edges.append(edge)

        low_edges = np.array(low_edges, dtype=np.int64)
        high_edges = np.array(high_edges, dtype=np.int64)

        self.edge_index_low = torch.tensor(low_edges, dtype=torch.long).t().contiguous().to(self.device)
        self.edge_index_high = torch.tensor(high_edges, dtype=torch.long).t().contiguous().to(self.device)

        self.edge_index_low = torch.cat(
            (self.edge_index_low, self.edge_index_low[[1, 0]]),
            dim=1
        )

        self.edge_index_high = torch.cat(
            (self.edge_index_high, self.edge_index_high[[1, 0]]),
            dim=1
        )
        # self.edge = concat 2 edge_index to make the graph undirected
        # self.edge_index = torch.cat((self.edge_index_low, self.edge_index_high), dim=1)

        # self.idl_gcn = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
        #                 num_layer=self.num_layer, has_feature=False, dropout=self.drop_rate, dim_latent=64,
        #                 device=self.device, features=self.id_embedding.weight)
        # self.idh_gcn = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
        #                 num_layer=self.num_layer, has_feature=False, dropout=self.drop_rate, dim_latent=64,
        #                 device=self.device, features=self.id_embedding.weight)

        self.full_gcn = GCN(
                        self.dataset,
                        batch_size,
                        num_user,
                        num_item,
                        dim_x,
                        self.aggr_mode,
                        num_layer=self.num_layer,
                        has_feature=False,
                        dropout=self.drop_rate,
                        dim_latent=64,
                        device=self.device,
                        features=self.id_embedding_full.weight
                    )

        self.mask_gcn = GCN(
            self.dataset,
            batch_size,
            num_user,
            num_item,
            dim_x,
            self.aggr_mode,
            num_layer=self.num_layer,
            has_feature=False,
            dropout=self.drop_rate,
            dim_latent=64,
            device=self.device,
            features=self.id_embedding_masked.weight
        )
        if config['fusion'] in ['add', 'pool']:
            pass
        elif config['fusion'] == 'Multi-Head Attention':
            self.multihead_attn = nn.MultiheadAttention(embed_dim=64, num_heads=4)
        elif config['fusion'] == 'Transformer':
            self.transformer = TransformerEncoder(64, num_heads= 4, layers=2)
        else:
            raise NotImplementedError
        


    def get_knn_adj_mat(self, mm_embeddings):
        context_norm = mm_embeddings.div(torch.norm(mm_embeddings, p=2, dim=-1, keepdim=True))
        sim = torch.mm(context_norm, context_norm.transpose(1, 0))
        _, knn_ind = torch.topk(sim, self.knn_k, dim=-1)
        adj_size = sim.size()
        del sim
        # construct sparse adj
        indices0 = torch.arange(knn_ind.shape[0]).to(self.device)
        indices0 = torch.unsqueeze(indices0, 1)
        indices0 = indices0.expand(-1, self.knn_k)
        indices = torch.stack((torch.flatten(indices0), torch.flatten(knn_ind)), 0)
        # norm
        return indices, self.compute_normalized_laplacian(indices, adj_size)
    
    def compute_normalized_laplacian(self, indices, adj_size):
        adj = torch.sparse.FloatTensor(indices, torch.ones_like(indices[0]), adj_size)
        row_sum = 1e-7 + torch.sparse.sum(adj, -1).to_dense()
        r_inv_sqrt = torch.pow(row_sum, -0.5)
        rows_inv_sqrt = r_inv_sqrt[indices[0]]
        cols_inv_sqrt = r_inv_sqrt[indices[1]]
        values = rows_inv_sqrt * cols_inv_sqrt
        return torch.sparse.FloatTensor(indices, values, adj_size)

    def pack_edge_index(self, inter_mat):
        rows = inter_mat.row
        cols = inter_mat.col + self.n_users
        return np.column_stack((rows, cols))

    def item_item(self, rep):
        h = rep
        for i in range(self.n_layers):
            h = torch.sparse.mm(self.mm_adj, h)
        return rep + h

    def get_user_mask(self):
        """Return one learned neighborhood-strength scalar per user."""
        return torch.sigmoid(self.user_mask_logits)

    def get_original_edge_mask(self, user_mask=None):
        """
        Expand user-level scalar masks to the original user-item edges.

        For every original interaction edge e=(u,i):
            edge_mask[e] = user_mask[u]
        """
        if user_mask is None:
            user_mask = self.get_user_mask()
        return user_mask[self.edge_user_ids]

    def _make_undirected_edge_mask(self, user_mask):
        """
        Convert a user-level mask [num_users] into an edge mask for
        self.edge_index = [original_edges, reverse_edges].
        """
        original_edge_mask = self.get_original_edge_mask(user_mask)
        return torch.cat(
            [original_edge_mask, original_edge_mask],
            dim=0
        )

    def _run_masked_world(self, user_mask):
        """
        Run the masked GCN under a specified user-level intervention.

        user_mask[u] controls the strength of ALL interaction messages
        incident to user u in the masked branch.
        """
        edge_mask = self._make_undirected_edge_mask(user_mask)

        mask_rep, mask_preference = self.mask_gcn(
            self.edge_index,
            self.id_embedding_masked.weight,
            edge_mask=edge_mask
        )

        return mask_rep, mask_preference

    def _build_result_embedding(self, full_rep, mask_rep):
        """
        Preserve the original fusion exactly:
            user = [full_user || masked_user]
            item = item-item-propagation([full_item || masked_item])
        """
        item_full = full_rep[self.num_user:]
        item_mask = mask_rep[self.num_user:]

        item_rep = torch.cat(
            (item_full, item_mask),
            dim=1
        )
        item_rep = self.item_item(item_rep)

        user_full = full_rep[:self.num_user]
        user_mask = mask_rep[:self.num_user]

        user_rep = torch.cat(
            (user_full, user_mask),
            dim=1
        )

        return torch.cat(
            (user_rep, item_rep),
            dim=0
        )

    def _score_result_embedding(
        self,
        result_embed,
        user_nodes,
        pos_item_nodes,
        neg_item_nodes
    ):
        user_tensor = result_embed[user_nodes]
        pos_item_tensor = result_embed[pos_item_nodes]
        neg_item_tensor = result_embed[neg_item_nodes]

        pos_scores = torch.sum(
            user_tensor * pos_item_tensor,
            dim=1
        )
        neg_scores = torch.sum(
            user_tensor * neg_item_tensor,
            dim=1
        )

        return pos_scores, neg_scores

    @staticmethod
    def _bpr_per_sample(pos_scores, neg_scores):
        """
        Per-sample BPR loss.

        This matches the monotonic objective used by the original code,
        but keeps the individual losses so that we can compare factual
        and counterfactual responses user-by-user.
        """
        margin = pos_scores - neg_scores
        return -torch.log2(
            torch.sigmoid(margin).clamp_min(1e-12)
        )

    @torch.no_grad()
    def get_user_mask_statistics(self):
        user_mask = self.get_user_mask().detach()

        return {
            'mean_keep': user_mask.mean().item(),
            'mean_attenuation': (1.0 - user_mask).mean().item(),
            'min_keep': user_mask.min().item(),
            'max_keep': user_mask.max().item(),
            'std_keep': user_mask.std(unbiased=False).item(),
        }

    def forward(self, interaction):
        user_nodes = interaction[0]
        pos_item_nodes = interaction[1] + self.n_users
        neg_item_nodes = interaction[2] + self.n_users

        # ============================================================
        # 1. Full factual graph branch
        # ============================================================
        self.full_rep, self.full_preference = self.full_gcn(
            self.edge_index,
            self.id_embedding_full.weight
        )

        # ============================================================
        # 2. Learned user-level neighborhood-strength branch
        # ============================================================
        user_mask = self.get_user_mask()

        self.mask_rep, self.mask_preference = self._run_masked_world(
            user_mask
        )

        # ============================================================
        # 3. Original fusion and prediction
        # ============================================================
        self.result_embed = self._build_result_embedding(
            self.full_rep,
            self.mask_rep
        )

        pos_scores, neg_scores = self._score_result_embedding(
            self.result_embed,
            user_nodes,
            pos_item_nodes,
            neg_item_nodes
        )

        return pos_scores, neg_scores

    def _counterfactual_response_loss(
        self,
        interaction,
        factual_per_sample_loss
    ):
        """
        Counterfactual Neighborhood Response Learning.

        For users appearing in the current mini-batch, probe:
            factual: m_u
            minus:   m_u - delta  (more compression)
            plus:    m_u + delta  (less compression)

        The two counterfactual worlds are DETACHED probes: they do not
        backpropagate through GCN parameters. Their only role is to tell
        us which local intervention direction seems better.

        Then create a pseudo-target for each active user's scalar mask:
            target = m_u - delta  if more compression is better
            target = m_u + delta  if less compression is better
            target = m_u          if factual is already best / stable

        A Smooth-L1 response loss moves only the learnable user scalar
        toward that local counterfactual target.
        """
        user_nodes = interaction[0]
        pos_item_nodes = interaction[1] + self.n_users
        neg_item_nodes = interaction[2] + self.n_users

        unique_users, inverse = torch.unique(
            user_nodes,
            sorted=False,
            return_inverse=True
        )

        # Current learned mask remains differentiable for the final
        # response loss. Counterfactual probe masks are detached.
        current_user_mask = self.get_user_mask()
        current_active_mask = current_user_mask[unique_users]

        with torch.no_grad():
            factual_mask_detached = current_user_mask.detach()

            # --------------------------------------------------------
            # Local intervention: only users in this batch are changed.
            # All other users remain at their learned factual masks.
            # --------------------------------------------------------
            minus_user_mask = factual_mask_detached.clone()
            plus_user_mask = factual_mask_detached.clone()

            minus_user_mask[unique_users] = torch.clamp(
                factual_mask_detached[unique_users] - self.cf_delta,
                min=0.0,
                max=1.0
            )

            plus_user_mask[unique_users] = torch.clamp(
                factual_mask_detached[unique_users] + self.cf_delta,
                min=0.0,
                max=1.0
            )

            # More-compression counterfactual world.
            minus_mask_rep, _ = self._run_masked_world(
                minus_user_mask
            )
            minus_result_embed = self._build_result_embedding(
                self.full_rep.detach(),
                minus_mask_rep
            )
            minus_pos, minus_neg = self._score_result_embedding(
                minus_result_embed,
                user_nodes,
                pos_item_nodes,
                neg_item_nodes
            )
            minus_loss = self._bpr_per_sample(
                minus_pos,
                minus_neg
            )

            # Less-compression counterfactual world.
            plus_mask_rep, _ = self._run_masked_world(
                plus_user_mask
            )
            plus_result_embed = self._build_result_embedding(
                self.full_rep.detach(),
                plus_mask_rep
            )
            plus_pos, plus_neg = self._score_result_embedding(
                plus_result_embed,
                user_nodes,
                pos_item_nodes,
                neg_item_nodes
            )
            plus_loss = self._bpr_per_sample(
                plus_pos,
                plus_neg
            )

            factual_loss = factual_per_sample_loss.detach()

            # --------------------------------------------------------
            # Determine the locally best world PER TRAINING SAMPLE.
            #
            # Index:
            #   0 -> m - delta : more compression
            #   1 -> m         : factual/stable
            #   2 -> m + delta : less compression
            # --------------------------------------------------------
            all_losses = torch.stack(
                [minus_loss, factual_loss, plus_loss],
                dim=1
            )

            best_world = torch.argmin(
                all_losses,
                dim=1
            )

            best_cf_loss = torch.minimum(
                minus_loss,
                plus_loss
            )

            improvement = (
                factual_loss - best_cf_loss
            ).clamp_min(0.0)

            # Do not react to tiny/noisy improvements if a threshold
            # is requested.
            has_useful_cf = (
                improvement > self.cf_min_improvement
            )

            sample_direction = torch.zeros_like(
                factual_loss
            )

            # -1 = move m down = MORE compression
            sample_direction[
                (best_world == 0) & has_useful_cf
            ] = -1.0

            # +1 = move m up = LESS compression
            sample_direction[
                (best_world == 2) & has_useful_cf
            ] = 1.0

            # --------------------------------------------------------
            # Aggregate sample-level responses into one response per
            # unique user in this batch.
            #
            # If a user has contradictory samples, the mean direction
            # naturally moves toward zero (stable).
            # --------------------------------------------------------
            direction_sum = torch.zeros(
                unique_users.numel(),
                device=user_nodes.device,
                dtype=factual_loss.dtype
            )
            count = torch.zeros_like(
                direction_sum
            )
            improvement_sum = torch.zeros_like(
                direction_sum
            )

            direction_sum.index_add_(
                0,
                inverse,
                sample_direction
            )
            improvement_sum.index_add_(
                0,
                inverse,
                improvement
            )
            count.index_add_(
                0,
                inverse,
                torch.ones_like(sample_direction)
            )

            mean_direction = (
                direction_sum
                / count.clamp_min(1.0)
            )

            mean_improvement = (
                improvement_sum
                / count.clamp_min(1.0)
            )

            # Counterfactual pseudo-target.
            target_active_mask = torch.clamp(
                current_active_mask.detach()
                + self.cf_delta * mean_direction,
                min=0.0,
                max=1.0
            )

        # ------------------------------------------------------------
        # Only this small loss backpropagates from the CF experiment.
        # It updates user_mask_logits toward the locally better
        # neighborhood-strength intervention.
        # ------------------------------------------------------------
        response_loss = F.smooth_l1_loss(
            current_active_mask,
            target_active_mask
        )

        with torch.no_grad():
            eps = 1e-8

            more = (
                mean_direction < -eps
            ).float().mean().item()

            less = (
                mean_direction > eps
            ).float().mean().item()

            stable = (
                mean_direction.abs() <= eps
            ).float().mean().item()

            self.cf_last_stats = {
                'response_loss': float(response_loss.detach().item()),
                'fraction_more_compression': float(more),
                'fraction_less_compression': float(less),
                'fraction_stable': float(stable),
                'mean_counterfactual_improvement': float(
                    mean_improvement.mean().item()
                ),
                'mean_direction': float(
                    mean_direction.mean().item()
                ),
            }

        return response_loss

    def calculate_loss(self, interaction):
        pos_scores, neg_scores = self.forward(interaction)

        factual_per_sample_loss = self._bpr_per_sample(
            pos_scores,
            neg_scores
        )

        main_loss = factual_per_sample_loss.mean()

        # ------------------------------------------------------------
        # Optional counterfactual response learning.
        #
        # interval=1 -> probe every training step.
        # interval=5 -> probe every 5th step to reduce cost.
        # ------------------------------------------------------------
        response_loss = main_loss.new_zeros(())

        use_cf_step = (
            self.training
            and self.cf_response_weight > 0.0
            and self.cf_response_interval > 0
            and (
                self._cf_train_step
                % self.cf_response_interval
                == 0
            )
        )

        if use_cf_step:
            response_loss = self._counterfactual_response_loss(
                interaction,
                factual_per_sample_loss
            )

        self._cf_train_step += 1

        total_loss = (
            main_loss
            + self.cf_response_weight * response_loss
        )

        return total_loss

    @torch.no_grad()
    def probe_counterfactual_response(self, interaction, delta=None):
        """
        Analysis helper.

        Returns per-sample ranking losses under:
            m_u - delta
            m_u
            m_u + delta

        This does NOT update parameters and is useful for plotting
        counterfactual response distributions after training.
        """
        if delta is None:
            delta = self.cf_delta

        user_nodes = interaction[0]
        pos_item_nodes = interaction[1] + self.n_users
        neg_item_nodes = interaction[2] + self.n_users

        # Recompute factual representations for a self-contained probe.
        full_rep, _ = self.full_gcn(
            self.edge_index,
            self.id_embedding_full.weight
        )

        factual_user_mask = self.get_user_mask().detach()

        factual_mask_rep, _ = self._run_masked_world(
            factual_user_mask
        )
        factual_result = self._build_result_embedding(
            full_rep,
            factual_mask_rep
        )
        factual_pos, factual_neg = self._score_result_embedding(
            factual_result,
            user_nodes,
            pos_item_nodes,
            neg_item_nodes
        )
        factual_loss = self._bpr_per_sample(
            factual_pos,
            factual_neg
        )

        unique_users = torch.unique(
            user_nodes,
            sorted=False
        )

        minus_user_mask = factual_user_mask.clone()
        plus_user_mask = factual_user_mask.clone()

        minus_user_mask[unique_users] = torch.clamp(
            factual_user_mask[unique_users] - delta,
            0.0,
            1.0
        )
        plus_user_mask[unique_users] = torch.clamp(
            factual_user_mask[unique_users] + delta,
            0.0,
            1.0
        )

        minus_rep, _ = self._run_masked_world(
            minus_user_mask
        )
        minus_result = self._build_result_embedding(
            full_rep,
            minus_rep
        )
        minus_pos, minus_neg = self._score_result_embedding(
            minus_result,
            user_nodes,
            pos_item_nodes,
            neg_item_nodes
        )
        minus_loss = self._bpr_per_sample(
            minus_pos,
            minus_neg
        )

        plus_rep, _ = self._run_masked_world(
            plus_user_mask
        )
        plus_result = self._build_result_embedding(
            full_rep,
            plus_rep
        )
        plus_pos, plus_neg = self._score_result_embedding(
            plus_result,
            user_nodes,
            pos_item_nodes,
            neg_item_nodes
        )
        plus_loss = self._bpr_per_sample(
            plus_pos,
            plus_neg
        )

        return {
            'user_nodes': user_nodes.detach(),
            'factual_mask': factual_user_mask[user_nodes].detach(),
            'minus_loss': minus_loss.detach(),
            'factual_loss': factual_loss.detach(),
            'plus_loss': plus_loss.detach(),
            'minus_margin': (minus_pos - minus_neg).detach(),
            'factual_margin': (factual_pos - factual_neg).detach(),
            'plus_margin': (plus_pos - plus_neg).detach(),
        }

    def get_cf_response_statistics(self):
        """Return diagnostics from the latest CF-response training step."""
        return dict(self.cf_last_stats)

    def full_sort_predict(self, interaction):
        user_tensor = self.result_embed[:self.n_users]
        item_tensor = self.result_embed[self.n_users:]

        temp_user_tensor = user_tensor[interaction[0], :]
        score_matrix = torch.matmul(
            temp_user_tensor,
            item_tensor.t()
        )
        return score_matrix

class GCN(torch.nn.Module):
    def __init__(self,datasets, batch_size, num_user, num_item, dim_id, aggr_mode, num_layer, has_feature, dropout,
                 dim_latent=None,device = None,features=None, user_profile=None):
        super(GCN, self).__init__()
        self.batch_size = batch_size
        self.num_user = num_user
        self.num_item = num_item
        self.datasets = datasets
        self.dim_id = dim_id
        self.dim_feat = features.size(1)
        self.dim_latent = dim_latent
        self.aggr_mode = aggr_mode
        self.has_feature = has_feature
        self.dropout = dropout
        self.device = device
        self.userprofile = user_profile

        if self.has_feature:
            self.preference = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
                np.random.randn(num_user, self.dim_latent), dtype=torch.float32, requires_grad=True),
                gain=1))
            self.conv_embed_1 = Base_gcn(self.dim_latent, self.dim_latent, aggr=self.aggr_mode)
        else:
            self.preference = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
                np.random.randn(num_user, self.dim_feat), dtype=torch.float32, requires_grad=True),
                gain=1))
            self.conv_embed_1 = Base_gcn(self.dim_latent, self.dim_latent, aggr=self.aggr_mode)

    def forward(self,edge_index,features, edge_mask = None):
        temp_features = features
        temp_profile = self.preference
        x = torch.cat((temp_profile, temp_features), dim=0)
        x = F.normalize(x)
        h = self.conv_embed_1(x, edge_index,edge_mask)  # equation 1
        h_1 = self.conv_embed_1(h, edge_index,edge_mask)  # equation 1
        h_2 = self.conv_embed_1(h_1, edge_index,edge_mask)

        x_hat =h + x + h_1 + h_2
        return x_hat, self.preference


class Base_gcn(MessagePassing):
    def __init__(self, in_channels, out_channels, normalize=True, bias=True, aggr='add', **kwargs):
        super(Base_gcn, self).__init__(aggr=aggr, **kwargs)
        self.aggr = aggr
        self.in_channels = in_channels
        self.out_channels = out_channels

    def forward(self, x, edge_index,edge_mask=None, size=None):
        # pdb.set_trace()

        if edge_mask is None:
            edge_mask = torch.ones(
                edge_index.size(1),
                device=x.device,
                dtype=x.dtype
            )

        if size is None:
            edge_index, _ = remove_self_loops(edge_index)
            # edge_index, _ = add_self_loops(edge_index, num_nodes=x.size(0))
        x = x.unsqueeze(-1) if x.dim() == 1 else x
        # pdb.set_trace()
        return self.propagate(edge_index, size=(x.size(0), x.size(0)), x=x, edge_mask = edge_mask)

    def message(self, x_j, edge_index, size,edge_mask):
        if self.aggr == 'add':
            # pdb.set_trace()
            row, col = edge_index
            deg = degree(row, size[0], dtype=x_j.dtype)
            deg_inv_sqrt = deg.pow(-0.5)
            deg_inv_sqrt[
            torch.isinf(deg_inv_sqrt)
            ] = 0

            norm = deg_inv_sqrt[row] * deg_inv_sqrt[col]
            # return norm.view(-1, 1) * x_j
            return (
                norm.view(-1, 1)
                * edge_mask.view(-1, 1)
                * x_j
            )
        return x_j

    def update(self, aggr_out):
        return aggr_out

    def __repr(self):
        return '{}({},{})'.format(self.__class__.__name__, self.in_channels, self.out_channels)


