# coding: utf-8
# 
#
# user-graph need to be generated by the following script
# tools/generate-u-u-matrix.py
import os
import math
import numpy as np
import scipy.sparse as sp
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn.conv import MessagePassing
from torch_geometric.utils import remove_self_loops, add_self_loops, degree
import torch_geometric

from common.abstract_recommender import GeneralRecommender
from common.loss import BPRLoss, EmbLoss
from common.init import xavier_uniform_initialization
from torch.nn import MultiheadAttention
# from .transformer import TransformerEncoder


def _cfg(config, key, default):
    """Read an optional config value without assuming config implements .get()."""
    try:
        value = config[key]
    except Exception:
        return default
    return default if value is None else value

class PREODIC_REMOVE(GeneralRecommender):
    def __init__(self, config, dataset):
        super(PREODIC_REMOVE, self).__init__(config, dataset)

        num_user = self.n_users
        num_item = self.n_items
        print('number of users: {}, number of items: {}'.format(num_user, num_item))
        
        batch_size = config['train_batch_size']         # not used
        dim_x = config['embedding_size']
        self.feat_embed_dim = config['feat_embed_dim']
        self.n_layers = config['n_mm_layers']
        self.knn_k = config['knn_k']

        self.batch_size = batch_size
        self.num_user = num_user
        self.num_item = num_item
        self.k = 40
        self.aggr_mode = config['aggr_mode']
        self.user_aggr_mode = 'softmax'
        self.num_layer = 1
        self.dataset = dataset
        self.reg_weight = config['reg_weight']
        self.drop_rate = 0.1
        self.t_rep = None
        self.t_preference = None
        self.dim_latent = 64
        self.mm_adj = None
        self.config = config

        # -------------------------------------------------------------
        # Efficient periodic personalized counterfactual objective.
        #
        # Normal batches:
        #     L = fused Full+Mask BPR only.
        #
        # Every cf_every batches:
        #     - free sufficiency from the already-computed Mask branch
        #     - ONE extra Mask-GCN pass after removing each active user's
        #       personalized top-mask interaction set.
        #
        # Thus:
        #     normal batch = 2 GCN passes  (Full + Mask)
        #     CF batch     = 3 GCN passes  (Full + Mask + Remove)
        #
        # With cf_every=5, average = 2.2 GCN passes / batch.
        # -------------------------------------------------------------
        self.cf_every = int(
            _cfg(config, 'cf_every', 5)
        )

        self.cf_top_ratio = float(
            _cfg(config, 'cf_top_ratio', 0.30)
        )

        self.cf_suff_weight = float(
            _cfg(config, 'cf_suff_weight', 0.005)
        )

        self.cf_suff_margin = float(
            _cfg(config, 'cf_suff_margin', 0.0)
        )

        self.cf_nec_weight = float(
            _cfg(config, 'cf_nec_weight', 0.01)
        )

        self.cf_nec_margin = float(
            _cfg(config, 'cf_nec_margin', 0.20)
        )

        # Users with fewer than this many graph edges are not used for
        # personalized top-k removal.
        self.cf_min_user_degree = int(
            _cfg(config, 'cf_min_user_degree', 2)
        )

        # Optional warmup. During warmup, train the original Full+Mask model
        # so that top-mask selection is not based on the initial all-0.5 mask.
        self.cf_warmup_steps = int(
            _cfg(config, 'cf_warmup_steps', 0)
        )

        # Formula in the proposed version:
        #   L_nec = softplus(m_remove - sg(m_mask) + delta)
        #
        # Keep True to match that formula.
        # Setting False allows the necessity loss to also strengthen the
        # observed Mask-branch margin directly.
        self.cf_detach_reference = bool(
            _cfg(config, 'cf_detach_reference', True)
        )

        self.cf_eps = 1e-8

        if self.cf_every < 1:
            raise ValueError("cf_every must be >= 1.")
        if not (0.0 < self.cf_top_ratio <= 1.0):
            raise ValueError("Require 0 < cf_top_ratio <= 1.")
        if self.cf_suff_weight < 0.0:
            raise ValueError("cf_suff_weight must be >= 0.")
        if self.cf_nec_weight < 0.0:
            raise ValueError("cf_nec_weight must be >= 0.")
        if self.cf_min_user_degree < 1:
            raise ValueError("cf_min_user_degree must be >= 1.")
        if self.cf_warmup_steps < 0:
            raise ValueError("cf_warmup_steps must be >= 0.")

        # Saved with state_dict, but never optimized.
        self.register_buffer(
            'cf_train_step',
            torch.zeros(
                (),
                dtype=torch.long,
                device=self.device
            )
        )

        dataset_path = os.path.abspath(config['data_path'] + config['dataset'])
        
        mm_adj_file = os.path.join(dataset_path, 'mm_adj_{}.pt'.format(self.knn_k))

        # self.id_embedding_low = nn.Embedding(num_item, self.feat_embed_dim)
        # self.id_embedding_high = nn.Embedding(num_item, self.feat_embed_dim)
        self.id_embedding_full = nn.Embedding(num_item, self.feat_embed_dim)
        self.id_embedding_masked = nn.Embedding(num_item, self.feat_embed_dim)

        self.mlp_item = nn.Linear(self.t_feat.shape[-1], self.dim_latent, bias=False)
        self.mlp_user = nn.Linear(self.user_feat.shape[-1], self.dim_latent, bias=False)

        indices, text_adj = self.get_knn_adj_mat(self.t_feat)
        self.mm_adj = text_adj

        train_interactions = dataset.inter_matrix(form='coo').astype(np.float32)

        edge_index = self.pack_edge_index(train_interactions)

        self.num_interactions = edge_index.shape[0]

        # -------------------------------------------------------------
        # User -> edge grouping for personalized removal.
        #
        # mask_logits has one value per unique forward interaction edge.
        # These buffers let us retrieve all edges incident to a user quickly.
        # -------------------------------------------------------------
        forward_user_ids_np = edge_index[:, 0].astype(np.int64)

        user_degree_np = np.bincount(
            forward_user_ids_np,
            minlength=self.num_user
        ).astype(np.int64)

        edge_order_np = np.argsort(
            forward_user_ids_np,
            kind='stable'
        ).astype(np.int64)

        user_ptr_np = np.zeros(
            self.num_user + 1,
            dtype=np.int64
        )
        user_ptr_np[1:] = np.cumsum(
            user_degree_np
        )

        self.register_buffer(
            'cf_user_degree',
            torch.tensor(
                user_degree_np,
                dtype=torch.long,
                device=self.device
            )
        )

        self.register_buffer(
            'cf_edge_order',
            torch.tensor(
                edge_order_np,
                dtype=torch.long,
                device=self.device
            )
        )

        self.register_buffer(
            'cf_user_ptr',
            torch.tensor(
                user_ptr_np,
                dtype=torch.long,
                device=self.device
            )
        )

        self.loss_components = {}

        edge_index = torch.tensor(edge_index, 
                                  dtype=torch.long,
                                  device = self.device).t().contiguous()

        self.edge_index = torch.cat(
                            [edge_index, edge_index[[1, 0]]],
                            dim=1
                        )

        self.mask_logits = nn.Parameter(
                            torch.zeros(
                                self.num_interactions,
                                device=self.device
                            )
                        )

        edge_index = self.pack_edge_index(train_interactions)

        item_ids = edge_index[:, 1] - self.num_user
        item_degree = np.bincount(item_ids, minlength=self.num_item)

        high_ratio = 0.10
        num_high = int(self.num_item * high_ratio)

        high_items = np.argsort(item_degree)[-num_high:]
        high_items = set(high_items.tolist())

        low_edges = []
        high_edges = []

        for edge in edge_index:
            item_id = edge[1] - self.num_user

            if item_id in high_items:
                high_edges.append(edge)
            else:
                low_edges.append(edge)

        low_edges = np.array(low_edges, dtype=np.int64)
        high_edges = np.array(high_edges, dtype=np.int64)

        self.edge_index_low = torch.tensor(low_edges, dtype=torch.long).t().contiguous().to(self.device)
        self.edge_index_high = torch.tensor(high_edges, dtype=torch.long).t().contiguous().to(self.device)

        self.edge_index_low = torch.cat(
            (self.edge_index_low, self.edge_index_low[[1, 0]]),
            dim=1
        )

        self.edge_index_high = torch.cat(
            (self.edge_index_high, self.edge_index_high[[1, 0]]),
            dim=1
        )
        # self.edge = concat 2 edge_index to make the graph undirected
        # self.edge_index = torch.cat((self.edge_index_low, self.edge_index_high), dim=1)

        # self.idl_gcn = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
        #                 num_layer=self.num_layer, has_feature=False, dropout=self.drop_rate, dim_latent=64,
        #                 device=self.device, features=self.id_embedding.weight)
        # self.idh_gcn = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
        #                 num_layer=self.num_layer, has_feature=False, dropout=self.drop_rate, dim_latent=64,
        #                 device=self.device, features=self.id_embedding.weight)

        self.full_gcn = GCN(
                        self.dataset,
                        batch_size,
                        num_user,
                        num_item,
                        dim_x,
                        self.aggr_mode,
                        num_layer=self.num_layer,
                        has_feature=False,
                        dropout=self.drop_rate,
                        dim_latent=64,
                        device=self.device,
                        features=self.id_embedding_full.weight
                    )

        self.mask_gcn = GCN(
            self.dataset,
            batch_size,
            num_user,
            num_item,
            dim_x,
            self.aggr_mode,
            num_layer=self.num_layer,
            has_feature=False,
            dropout=self.drop_rate,
            dim_latent=64,
            device=self.device,
            features=self.id_embedding_masked.weight
        )
        if config['fusion'] in ['add', 'pool']:
            pass
        elif config['fusion'] == 'Multi-Head Attention':
            self.multihead_attn = nn.MultiheadAttention(embed_dim=64, num_heads=4)
        elif config['fusion'] == 'Transformer':
            self.transformer = TransformerEncoder(64, num_heads= 4, layers=2)
        else:
            raise NotImplementedError
        


    def get_knn_adj_mat(self, mm_embeddings):
        context_norm = mm_embeddings.div(torch.norm(mm_embeddings, p=2, dim=-1, keepdim=True))
        sim = torch.mm(context_norm, context_norm.transpose(1, 0))
        _, knn_ind = torch.topk(sim, self.knn_k, dim=-1)
        adj_size = sim.size()
        del sim
        # construct sparse adj
        indices0 = torch.arange(knn_ind.shape[0]).to(self.device)
        indices0 = torch.unsqueeze(indices0, 1)
        indices0 = indices0.expand(-1, self.knn_k)
        indices = torch.stack((torch.flatten(indices0), torch.flatten(knn_ind)), 0)
        # norm
        return indices, self.compute_normalized_laplacian(indices, adj_size)
    
    def compute_normalized_laplacian(self, indices, adj_size):
        adj = torch.sparse.FloatTensor(indices, torch.ones_like(indices[0]), adj_size)
        row_sum = 1e-7 + torch.sparse.sum(adj, -1).to_dense()
        r_inv_sqrt = torch.pow(row_sum, -0.5)
        rows_inv_sqrt = r_inv_sqrt[indices[0]]
        cols_inv_sqrt = r_inv_sqrt[indices[1]]
        values = rows_inv_sqrt * cols_inv_sqrt
        return torch.sparse.FloatTensor(indices, values, adj_size)

    def pack_edge_index(self, inter_mat):
        rows = inter_mat.row
        cols = inter_mat.col + self.n_users
        return np.column_stack((rows, cols))

    def item_item(self, rep):
        h = rep
        for i in range(self.n_layers):
            h = torch.sparse.mm(self.mm_adj, h)
        return rep + h

    def fuse_full_and_mask(self, full_rep, mask_rep):
        """
        Preserve the original fusion exactly:

            user_final = [user_full || user_mask]
            item_final = item_item([item_full || item_mask])
        """
        item_full = full_rep[self.num_user:]
        item_mask = mask_rep[self.num_user:]

        item_rep = torch.cat(
            (item_full, item_mask),
            dim=1
        )
        item_rep = self.item_item(
            item_rep
        )

        user_full = full_rep[:self.num_user]
        user_mask = mask_rep[:self.num_user]

        user_rep = torch.cat(
            (user_full, user_mask),
            dim=1
        )

        return torch.cat(
            (user_rep, item_rep),
            dim=0
        )

    def pairwise_scores(self, representation, interaction):
        """Pairwise BPR scores from a joint user-item representation."""
        user_nodes = interaction[0]
        pos_item_nodes = interaction[1] + self.n_users
        neg_item_nodes = interaction[2] + self.n_users

        user_tensor = representation[
            user_nodes
        ]
        pos_item_tensor = representation[
            pos_item_nodes
        ]
        neg_item_tensor = representation[
            neg_item_nodes
        ]

        pos_scores = torch.sum(
            user_tensor * pos_item_tensor,
            dim=1
        )
        neg_scores = torch.sum(
            user_tensor * neg_item_tensor,
            dim=1
        )

        return pos_scores, neg_scores

    def masked_branch_scores(
        self,
        mask_rep,
        interaction
    ):
        """
        Score ONLY the specialized Mask branch.

        The baseline applies item_item() after concatenation. Because that
        propagation is linear and acts independently on embedding dimensions,
        applying item_item() to the Mask item block alone gives the exact Mask
        contribution to the concatenated dot-product score.
        """
        user_mask = mask_rep[
            :self.num_user
        ]

        item_mask = mask_rep[
            self.num_user:
        ]
        item_mask = self.item_item(
            item_mask
        )

        user_nodes = interaction[0]
        pos_item_ids = interaction[1]
        neg_item_ids = interaction[2]

        pos_scores = torch.sum(
            user_mask[user_nodes]
            * item_mask[pos_item_ids],
            dim=1
        )

        neg_scores = torch.sum(
            user_mask[user_nodes]
            * item_mask[neg_item_ids],
            dim=1
        )

        return pos_scores, neg_scores

    def build_personalized_remove_mask(
        self,
        base_mask,
        batch_users
    ):
        """
        For every UNIQUE eligible user in the current mini-batch:

            S_u = top ceil(cf_top_ratio * degree_u) edges by learned mask.

        Counterfactual:
            remove exactly S_u from that user's graph neighborhood.

        Every other edge remains exactly at its learned base_mask value.

        Top-k membership is discrete, so selection is performed from
        base_mask.detach(). This avoids unstable gradients through top-k.

        Returns:
            remove_mask:     [E]
            selected_top:    [E] bool
            eligible_users:  unique eligible users in this batch
        """
        unique_users = torch.unique(
            batch_users
        )

        unique_degrees = self.cf_user_degree[
            unique_users
        ]

        eligible_users = unique_users[
            unique_degrees
            >= self.cf_min_user_degree
        ]

        selected_top = torch.zeros(
            self.num_interactions,
            dtype=torch.bool,
            device=base_mask.device
        )

        with torch.no_grad():
            detached_mask = base_mask.detach()

            for user_id_tensor in eligible_users:
                u = int(
                    user_id_tensor.item()
                )

                start = int(
                    self.cf_user_ptr[u].item()
                )
                end = int(
                    self.cf_user_ptr[u + 1].item()
                )

                if end <= start:
                    continue

                edge_ids = self.cf_edge_order[
                    start:end
                ]

                degree_u = end - start

                k = max(
                    1,
                    int(
                        math.ceil(
                            self.cf_top_ratio
                            * degree_u
                        )
                    )
                )
                k = min(
                    k,
                    degree_u
                )

                if k == degree_u:
                    chosen = edge_ids
                else:
                    local_mask = detached_mask[
                        edge_ids
                    ]

                    local_top = torch.topk(
                        local_mask,
                        k=k,
                        largest=True,
                        sorted=False
                    ).indices

                    chosen = edge_ids[
                        local_top
                    ]

                selected_top[
                    chosen
                ] = True

        remove_gate = (
            ~selected_top
        ).to(
            dtype=base_mask.dtype
        )

        remove_mask = (
            base_mask
            * remove_gate
        )

        return (
            remove_mask,
            selected_top,
            eligible_users
        )

    def forward(self, interaction, return_aux=False):
        # -------------------------------------------------------------
        # Full/global branch.
        # -------------------------------------------------------------
        self.full_rep, self.full_preference = self.full_gcn(
            self.edge_index,
            self.id_embedding_full.weight
        )

        # -------------------------------------------------------------
        # Learnable Mask/specialized branch.
        # -------------------------------------------------------------
        mask = torch.sigmoid(
            self.mask_logits
        )

        edge_mask = torch.cat(
            [mask, mask],
            dim=0
        )

        self.mask_rep, self.mask_preference = self.mask_gcn(
            self.edge_index,
            self.id_embedding_masked.weight,
            edge_mask=edge_mask
        )

        # Exact original [Full || Mask] representation.
        self.result_embed = self.fuse_full_and_mask(
            self.full_rep,
            self.mask_rep
        )

        pos_scores, neg_scores = self.pairwise_scores(
            self.result_embed,
            interaction
        )

        if not return_aux:
            return pos_scores, neg_scores

        # The Mask-only pairwise contribution is available without
        # another GCN propagation.
        mask_pos_scores, mask_neg_scores = self.masked_branch_scores(
            self.mask_rep,
            interaction
        )

        aux = {
            'mask': mask,
            'mask_pos_scores': mask_pos_scores,
            'mask_neg_scores': mask_neg_scores,
        }

        return (
            pos_scores,
            neg_scores,
            aux
        )

    def calculate_loss(self, interaction):
        """
        Efficient periodic personalized counterfactual objective.

        Normal batch:
            L = L_BPR

        Every cf_every batches (after optional warmup):
            L = L_BPR
                + cf_suff_weight * L_suff
                + cf_nec_weight  * L_nec

        Free sufficiency:
            m_mask = s_mask(u,i+) - s_mask(u,i-)

            L_suff = softplus(cf_suff_margin - m_mask)

        Personalized REMOVE necessity:
            S_u = top-mask incident edges for each active user
            M_remove = M * (1 - S)

            m_remove = Mask-GCN margin after removing S_u

            L_nec =
                softplus(
                    m_remove
                    - stopgrad(m_mask)
                    + cf_nec_margin
                )

        Only the REMOVE world needs one extra GCN pass.
        """

        # Count optimizer/loss calls. First CF step occurs at cf_every,
        # not at the first mini-batch.
        with torch.no_grad():
            self.cf_train_step.add_(1)

        current_step = int(
            self.cf_train_step.item()
        )

        cf_enabled = (
            self.cf_suff_weight > 0.0
            or self.cf_nec_weight > 0.0
        )

        do_cf = (
            cf_enabled
            and current_step > self.cf_warmup_steps
            and (
                (
                    current_step
                    - self.cf_warmup_steps
                )
                % self.cf_every
                == 0
            )
        )

        # -------------------------------------------------------------
        # Normal batch: preserve the original baseline path.
        # -------------------------------------------------------------
        if not do_cf:
            pos_scores, neg_scores = self.forward(
                interaction,
                return_aux=False
            )

            bpr_loss = -torch.mean(
                torch.log2(
                    torch.sigmoid(
                        pos_scores - neg_scores
                    )
                )
            )

            self.loss_components = {
                'step': current_step,
                'cf_active': 0,
                'total': float(
                    bpr_loss.detach().cpu()
                ),
                'bpr': float(
                    bpr_loss.detach().cpu()
                ),
            }

            return bpr_loss

        # -------------------------------------------------------------
        # CF batch: the normal Full + Mask pass.
        # -------------------------------------------------------------
        (
            pos_scores,
            neg_scores,
            aux
        ) = self.forward(
            interaction,
            return_aux=True
        )

        fused_margin = (
            pos_scores
            - neg_scores
        )

        bpr_loss = -torch.mean(
            torch.log2(
                torch.sigmoid(
                    fused_margin
                )
            )
        )

        mask_margin = (
            aux['mask_pos_scores']
            - aux['mask_neg_scores']
        )

        # -------------------------------------------------------------
        # FREE sufficiency:
        #
        # The normal Mask representation is already available.
        # No extra GCN pass is needed.
        # -------------------------------------------------------------
        suff_per_sample = (
            F.softplus(
                self.cf_suff_margin
                - mask_margin
            )
            / math.log(2.0)
        )

        suff_loss = (
            suff_per_sample.mean()
        )

        # -------------------------------------------------------------
        # Build the personalized top-mask sets and REMOVE them.
        # -------------------------------------------------------------
        (
            remove_mask,
            selected_top,
            eligible_users
        ) = self.build_personalized_remove_mask(
            base_mask=aux['mask'],
            batch_users=interaction[0]
        )

        # If there are no eligible users, keep only BPR + free sufficiency.
        if eligible_users.numel() == 0:
            total_loss = (
                bpr_loss
                + self.cf_suff_weight
                * suff_loss
            )

            self.loss_components = {
                'step': current_step,
                'cf_active': 1,
                'eligible_user_count': 0,
                'total': float(
                    total_loss.detach().cpu()
                ),
                'bpr': float(
                    bpr_loss.detach().cpu()
                ),
                'suff_loss': float(
                    suff_loss.detach().cpu()
                ),
                'nec_loss': 0.0,
                'mask_margin_mean': float(
                    mask_margin.mean()
                    .detach()
                    .cpu()
                ),
                'mask_mean': float(
                    aux['mask'].mean()
                    .detach()
                    .cpu()
                ),
            }

            return total_loss

        # -------------------------------------------------------------
        # ONE extra GCN pass: Mask graph after personalized top-edge removal.
        # -------------------------------------------------------------
        remove_edge_mask = torch.cat(
            [remove_mask, remove_mask],
            dim=0
        )

        remove_mask_rep, _ = self.mask_gcn(
            self.edge_index,
            self.id_embedding_masked.weight,
            edge_mask=remove_edge_mask
        )

        remove_pos_scores, remove_neg_scores = self.masked_branch_scores(
            remove_mask_rep,
            interaction
        )

        remove_margin = (
            remove_pos_scores
            - remove_neg_scores
        )

        # Only samples whose user was eligible should train necessity.
        eligible_sample = (
            self.cf_user_degree[
                interaction[0]
            ]
            >= self.cf_min_user_degree
        ).to(
            dtype=mask_margin.dtype
        )

        if self.cf_detach_reference:
            mask_reference = (
                mask_margin.detach()
            )
        else:
            mask_reference = (
                mask_margin
            )

        nec_per_sample = (
            F.softplus(
                remove_margin
                - mask_reference
                + self.cf_nec_margin
            )
            / math.log(2.0)
        )

        nec_loss = (
            eligible_sample
            * nec_per_sample
        ).sum() / (
            eligible_sample.sum()
            + self.cf_eps
        )

        total_loss = (
            bpr_loss
            + self.cf_suff_weight
            * suff_loss
            + self.cf_nec_weight
            * nec_loss
        )

        # -------------------------------------------------------------
        # Diagnostics.
        # -------------------------------------------------------------
        with torch.no_grad():
            necessity_drop = (
                mask_margin
                - remove_margin
            )

            selected_mask_mean = (
                aux['mask'][
                    selected_top
                ].mean()
                if selected_top.any()
                else torch.tensor(
                    0.0,
                    device=aux['mask'].device
                )
            )

            selected_fraction = (
                selected_top.float().mean()
            )

            valid = (
                eligible_sample > 0
            )

            if valid.any():
                nec_satisfied = (
                    necessity_drop[valid]
                    >= self.cf_nec_margin
                ).float().mean()
            else:
                nec_satisfied = torch.tensor(
                    0.0,
                    device=aux['mask'].device
                )

            self.loss_components = {
                'step': current_step,
                'cf_active': 1,
                'eligible_user_count': int(
                    eligible_users.numel()
                ),
                'total': float(
                    total_loss.detach().cpu()
                ),
                'bpr': float(
                    bpr_loss.detach().cpu()
                ),
                'suff_loss': float(
                    suff_loss.detach().cpu()
                ),
                'nec_loss': float(
                    nec_loss.detach().cpu()
                ),
                'weighted_suff_loss': float(
                    (
                        self.cf_suff_weight
                        * suff_loss
                    )
                    .detach()
                    .cpu()
                ),
                'weighted_nec_loss': float(
                    (
                        self.cf_nec_weight
                        * nec_loss
                    )
                    .detach()
                    .cpu()
                ),
                'mask_margin_mean': float(
                    mask_margin.mean()
                    .detach()
                    .cpu()
                ),
                'remove_margin_mean': float(
                    remove_margin.mean()
                    .detach()
                    .cpu()
                ),
                'necessity_drop_mean': float(
                    necessity_drop.mean()
                    .detach()
                    .cpu()
                ),
                'necessity_satisfied_fraction': float(
                    nec_satisfied
                    .detach()
                    .cpu()
                ),
                'selected_edge_fraction_global': float(
                    selected_fraction
                    .detach()
                    .cpu()
                ),
                'selected_mask_mean': float(
                    selected_mask_mean
                    .detach()
                    .cpu()
                ),
                'mask_mean': float(
                    aux['mask'].mean()
                    .detach()
                    .cpu()
                ),
            }

        return total_loss

    def full_sort_predict(self, interaction):
        user_tensor = self.result_embed[:self.n_users]
        item_tensor = self.result_embed[self.n_users:]

        temp_user_tensor = user_tensor[interaction[0], :]
        score_matrix = torch.matmul(temp_user_tensor, item_tensor.t())
        return score_matrix

class GCN(torch.nn.Module):
    def __init__(self,datasets, batch_size, num_user, num_item, dim_id, aggr_mode, num_layer, has_feature, dropout,
                 dim_latent=None,device = None,features=None, user_profile=None):
        super(GCN, self).__init__()
        self.batch_size = batch_size
        self.num_user = num_user
        self.num_item = num_item
        self.datasets = datasets
        self.dim_id = dim_id
        self.dim_feat = features.size(1)
        self.dim_latent = dim_latent
        self.aggr_mode = aggr_mode
        self.has_feature = has_feature
        self.dropout = dropout
        self.device = device
        self.userprofile = user_profile

        if self.has_feature:
            self.preference = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
                np.random.randn(num_user, self.dim_latent), dtype=torch.float32, requires_grad=True),
                gain=1))
            self.conv_embed_1 = Base_gcn(self.dim_latent, self.dim_latent, aggr=self.aggr_mode)
        else:
            self.preference = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
                np.random.randn(num_user, self.dim_feat), dtype=torch.float32, requires_grad=True),
                gain=1))
            self.conv_embed_1 = Base_gcn(self.dim_latent, self.dim_latent, aggr=self.aggr_mode)

    def forward(self,edge_index,features, edge_mask = None):
        temp_features = features
        temp_profile = self.preference
        x = torch.cat((temp_profile, temp_features), dim=0)
        x = F.normalize(x)
        h = self.conv_embed_1(x, edge_index,edge_mask)  # equation 1
        h_1 = self.conv_embed_1(h, edge_index,edge_mask)  # equation 1
        h_2 = self.conv_embed_1(h_1, edge_index,edge_mask)

        x_hat =h + x + h_1 + h_2
        return x_hat, self.preference


class Base_gcn(MessagePassing):
    def __init__(self, in_channels, out_channels, normalize=True, bias=True, aggr='add', **kwargs):
        super(Base_gcn, self).__init__(aggr=aggr, **kwargs)
        self.aggr = aggr
        self.in_channels = in_channels
        self.out_channels = out_channels

    def forward(self, x, edge_index,edge_mask=None, size=None):
        # pdb.set_trace()

        if edge_mask is None:
            edge_mask = torch.ones(
                edge_index.size(1),
                device=x.device,
                dtype=x.dtype
            )

        if size is None:
            edge_index, _ = remove_self_loops(edge_index)
            # edge_index, _ = add_self_loops(edge_index, num_nodes=x.size(0))
        x = x.unsqueeze(-1) if x.dim() == 1 else x
        # pdb.set_trace()
        return self.propagate(edge_index, size=(x.size(0), x.size(0)), x=x, edge_mask = edge_mask)

    def message(self, x_j, edge_index, size,edge_mask):
        if self.aggr == 'add':
            # pdb.set_trace()
            row, col = edge_index
            deg = degree(row, size[0], dtype=x_j.dtype)
            deg_inv_sqrt = deg.pow(-0.5)
            deg_inv_sqrt[
            torch.isinf(deg_inv_sqrt)
            ] = 0

            norm = deg_inv_sqrt[row] * deg_inv_sqrt[col]
            # return norm.view(-1, 1) * x_j
            return (
                norm.view(-1, 1)
                * edge_mask.view(-1, 1)
                * x_j
            )
        return x_j

    def update(self, aggr_out):
        return aggr_out

    def __repr(self):
        return '{}({},{})'.format(self.__class__.__name__, self.in_channels, self.out_channels)


